"""Stage a single-speaker Tone Perfect reference-voice pack for the app.

The tone ear was retrained on Tone Perfect (spike/RESULTS.md); this makes the
same corpus double as the "hear it correctly" voice for isolated-syllable
drills. Ear and mouth then share one ground truth: what the classifier grades
against is what the learner hears.

Picks one speaker (FV1 — highest tone canonical-ness in the leave-one-speaker-out
eval, 98.8%; the female voices are acoustically identical, same mastered
session), builds a hanzi/pinyin -> clip index (dropping polyphonic hanzi, which
can't be voiced unambiguously from the character alone), and copies that
speaker's 1,640 isolated-syllable mp3s into the app's /data mount.

The clips + index are runtime DATA (gitignored, live under /data next to learner
state), regenerated by this script — not baked into the image or committed.
Only single syllables are covered on purpose: stitched isolated clips sound
wrong for real words (no sandhi/coarticulation), so words/sentences stay on TTS.
"""
import json
import pathlib
import re
import shutil
import sys
from xml.etree import ElementTree as ET

HERE = pathlib.Path(__file__).parent
CORPUS = HERE.parent / "Tone perfect data set"
XML_DIR = CORPUS / "tone_perfect_all_xml" / "tone_perfect_xml"
MP3_DIR = CORPUS / "tone_perfect_all_mp3" / "tone_perfect"

SPEAKER = "FV1"
# in-container this is /data/tone_perfect_ref; on the host it's the bind-mount
DEST = pathlib.Path(sys.argv[1] if len(sys.argv) > 1
                    else "/home/phil/PersonalProjects/LanguageTutor-data/tone_perfect_ref")

_HAN = re.compile(r"[㐀-鿿]")


def build_index():
    """{hanzi/pinyin -> clip filename}, polyphonic hanzi excluded."""
    hanzi_syllables = {}   # hanzi -> set of syllables it can realize (for polyphone check)
    pinyin_map, numeric_map, syllable_file = {}, {}, {}
    for xml in sorted(XML_DIR.glob(f"*_{SPEAKER}_CUSTOM.xml")):
        root = ET.parse(xml).getroot()
        syllable = root.findtext("syllable")          # e.g. "ma1"
        pinyin = root.findtext("pinyin")              # e.g. "mā"
        fname = f"{syllable}_{SPEAKER}_MP3.mp3"
        if not (MP3_DIR / fname).exists():
            continue
        syllable_file[syllable] = fname
        pinyin_map[pinyin] = fname
        numeric_map[syllable] = fname
        forms = [x.text for x in root.findall("character_forms") if x.text]
        simplified = [c.findtext("simplified") for c in root.findall("character")]
        chars = {h for group in forms for h in group.split()} | {s for s in simplified if s}
        for h in chars:
            if _HAN.match(h):
                hanzi_syllables.setdefault(h, set()).add(syllable)

    polyphones = {h for h, syls in hanzi_syllables.items() if len(syls) > 1}
    hanzi_map = {h: syllable_file[next(iter(syls))]
                 for h, syls in hanzi_syllables.items()
                 if h not in polyphones and next(iter(syls)) in syllable_file}
    return {
        "speaker": SPEAKER,
        "hanzi": dict(sorted(hanzi_map.items())),
        "pinyin": dict(sorted(pinyin_map.items())),
        "numeric": dict(sorted(numeric_map.items())),
    }, polyphones


def main():
    index, polyphones = build_index()
    DEST.mkdir(parents=True, exist_ok=True)
    clips = sorted(set(index["hanzi"].values()) | set(index["pinyin"].values()))
    copied = 0
    for fname in clips:
        dst = DEST / fname
        if not dst.exists():
            shutil.copy2(MP3_DIR / fname, dst)
            copied += 1
    (DEST / "index.json").write_text(json.dumps(index, ensure_ascii=False, indent=1))
    print(f"speaker {SPEAKER}: {len(index['hanzi'])} hanzi, "
          f"{len(index['pinyin'])} syllables indexed "
          f"({len(polyphones)} polyphonic hanzi dropped)")
    print(f"clips: {len(clips)} referenced, {copied} newly copied -> {DEST}")


if __name__ == "__main__":
    main()
