"""The graded reader — reading from zero to full stories, as data.

A ladder of levels (R0 single characters → R6 a full story) of ORIGINAL
tokenized texts: every word carries its pinyin and gloss so the UI can make it
tappable and speakable, and every text names the few new words it introduces.
Vocabulary builds slowly and deliberately: a text pre-teaches its new words,
the learner reads, answers comprehension questions, and on completion the new
words enter the SRS deck (learner.add_word) — reading feeds reviews.

Unlocks are sequential (finish a level to open the next) but the speaking
stage sets a floor so a placed learner isn't stuck reading single characters:
stage index k opens levels 0..k outright.

Text format: sentences are written in a compact notation and expanded by
_s() — tokens separated by spaces, each word as hanzi|pinyin|gloss (multi-
syllable pinyin and multi-word glosses use _ for spaces); bare punctuation
stands alone. Dialogue lines carry a speaker.
"""


def _s(line, who=None):
    toks = []
    for part in line.split():
        bits = part.split("|")
        if len(bits) == 3:
            toks.append({"z": bits[0], "p": bits[1].replace("_", " "),
                         "e": bits[2].replace("_", " ")})
        else:
            toks.append({"z": part, "p": "", "e": ""})
    return {"who": who, "t": toks}


LEVELS = [
    {"id": "R0", "idx": 0, "zh": "认字", "name": "First characters", "ruby": True,
     "desc": "Single characters, one at a time — hear each one, see its shape mean something."},
    {"id": "R1", "idx": 1, "zh": "词", "name": "Characters make words", "ruby": True,
     "desc": "Two characters snap together and mean something new — the writing system's superpower."},
    {"id": "R2", "idx": 2, "zh": "句", "name": "First sentences", "ruby": True,
     "desc": "Real sentences built from characters you know. Pinyin still rides above."},
    {"id": "R3", "idx": 3, "zh": "对话", "name": "Dialogues", "ruby": False,
     "desc": "Two people talking. Pinyin fades — tap any word you need."},
    {"id": "R4", "idx": 4, "zh": "段", "name": "Paragraphs", "ruby": False,
     "desc": "Connected sentences that tell one small thing about a day."},
    {"id": "R5", "idx": 5, "zh": "小故事", "name": "Short stories", "ruby": False,
     "desc": "A beginning, a middle, and an end — your first real stories."},
    {"id": "R6", "idx": 6, "zh": "故事", "name": "A full story", "ruby": False,
     "desc": "Several paragraphs, one story, no training wheels."},
    {"id": "R7", "idx": 7, "zh": "长篇", "name": "Chaptered reading", "ruby": False,
     "desc": "Longer chapters that read like native material, still with tappable support."},
]

# (hanzi, pinyin, english, tones) — added to the SRS deck when the text is done
TEXTS = [
    # ── R0 — single characters ────────────────────────────────────────────────
    {"id": "r0-1", "level": "R0", "title": "一 二 三 四 五", "title_en": "Counting: one to five",
     "intro": "Your first characters count: 一 二 三 are literally counting rods. "
              "Tap each one and hear it.",
     "note": "Reading tip: the little circle 。 is the Chinese full stop — it ends "
             "a sentence exactly like a period.",
     "new_words": [("一", "yī", "one", [1]), ("二", "èr", "two", [4]),
                   ("三", "sān", "three", [1]), ("四", "sì", "four", [4]),
                   ("五", "wǔ", "five", [3])],
     "sentences": [_s("一|yī|one"), _s("二|èr|two"), _s("三|sān|three"),
                   _s("四|sì|four"), _s("五|wǔ|five")],
     "en": "One. Two. Three. Four. Five.",
     "qs": [{"q": "Which character means “four”?", "choices": ["四", "五", "二", "一"], "a": 0},
            {"q": "How is 三 read?", "choices": ["sān", "sì", "èr", "wǔ"], "a": 0}]},
    {"id": "r0-2", "level": "R0", "title": "六 七 八 九 十", "title_en": "Counting: six to ten",
     "intro": "The second half of counting. With these ten characters you can read "
              "any number to ninety-nine — 十一 is ten-one, eleven; 二十 is two-tens, twenty.",
     "new_words": [("六", "liù", "six", [4]), ("七", "qī", "seven", [1]),
                   ("八", "bā", "eight", [1]), ("九", "jiǔ", "nine", [3]),
                   ("十", "shí", "ten", [2])],
     "sentences": [_s("六|liù|six"), _s("七|qī|seven"), _s("八|bā|eight"),
                   _s("九|jiǔ|nine"), _s("十|shí|ten"),
                   _s("十|shí|ten 一|yī|one"), _s("二|èr|two 十|shí|ten")],
     "en": "Six. Seven. Eight. Nine. Ten. Eleven (ten-one). Twenty (two-tens).",
     "qs": [{"q": "Which character means “nine”?", "choices": ["九", "六", "七", "八"], "a": 0},
            {"q": "十一 (ten-one) means…", "choices": ["eleven", "twelve", "twenty", "one"], "a": 0},
            {"q": "二十 (two-tens) means…", "choices": ["twenty", "twelve", "eleven", "two"], "a": 0}]},
    {"id": "r0-3", "level": "R0", "title": "人 我 你 他", "title_en": "People",
     "intro": "人 is a person walking. From it: I, you, and he.",
     "new_words": [("人", "rén", "person", [2]), ("我", "wǒ", "I, me", [3]),
                   ("你", "nǐ", "you", [3]), ("他", "tā", "he, him", [1])],
     "sentences": [_s("人|rén|person"), _s("我|wǒ|I"), _s("你|nǐ|you"), _s("他|tā|he")],
     "en": "Person. I. You. He.",
     "qs": [{"q": "Which one is “I”?", "choices": ["我", "你", "他", "人"], "a": 0},
            {"q": "他 means…", "choices": ["he", "you", "person", "I"], "a": 0}]},
    {"id": "r0-4", "level": "R0", "title": "大 小 好 口", "title_en": "Big, small, good",
     "intro": "大 is a person with arms stretched wide — big. 口 is an open mouth.",
     "new_words": [("大", "dà", "big", [4]), ("小", "xiǎo", "small", [3]),
                   ("好", "hǎo", "good", [3]), ("口", "kǒu", "mouth", [3])],
     "sentences": [_s("大|dà|big"), _s("小|xiǎo|small"), _s("好|hǎo|good"), _s("口|kǒu|mouth")],
     "en": "Big. Small. Good. Mouth.",
     "qs": [{"q": "Which character means “small”?", "choices": ["小", "大", "口", "好"], "a": 0},
            {"q": "好 means…", "choices": ["good", "big", "mouth", "small"], "a": 0}]},
    {"id": "r0-5", "level": "R0", "title": "日 月 山 水", "title_en": "Sun, moon, mountain, water",
     "intro": "Four little pictures: the sun, a crescent moon, three peaks, and flowing water.",
     "new_words": [("日", "rì", "sun; day", [4]), ("月", "yuè", "moon; month", [4]),
                   ("山", "shān", "mountain", [1]), ("水", "shuǐ", "water", [3])],
     "sentences": [_s("日|rì|sun"), _s("月|yuè|moon"), _s("山|shān|mountain"), _s("水|shuǐ|water")],
     "en": "Sun. Moon. Mountain. Water.",
     "qs": [{"q": "山 is a picture of…", "choices": ["mountain peaks", "the sun", "a mouth", "water"], "a": 0},
            {"q": "Which character means “water”?", "choices": ["水", "山", "月", "日"], "a": 0}]},
    {"id": "r0-6", "level": "R0", "title": "女 子 马 妈 吗", "title_en": "Woman, child, horse, mom",
     "intro": "These shapes become family words and questions. 马 gives the sound; 女 changes the meaning.",
     "new_words": [("女", "nǚ", "woman", [3]), ("子", "zǐ", "child", [3]),
                   ("马", "mǎ", "horse", [3]), ("妈", "mā", "mom", [1]),
                   ("吗", "ma", "question word", [5])],
     "sentences": [_s("女|nǚ|woman"), _s("子|zǐ|child"), _s("马|mǎ|horse"),
                   _s("妈|mā|mom"), _s("吗|ma|question_word")],
     "en": "Woman. Child. Horse. Mom. Question word.",
     "qs": [{"q": "Which character means “horse”?", "choices": ["马", "妈", "吗", "女"], "a": 0},
            {"q": "Which one turns a sentence into a question?", "choices": ["吗", "妈", "子", "马"], "a": 0}]},
    {"id": "r0-7", "level": "R0", "title": "明 也 们 田", "title_en": "Bright, also, plural, field",
     "intro": "日 plus 月 makes 明, bright. 们 later turns 我 into 我们 — we.",
     "new_words": [("明", "míng", "bright", [2]), ("也", "yě", "also", [3]),
                   ("们", "men", "plural marker", [5]), ("田", "tián", "field", [2])],
     "sentences": [_s("明|míng|bright"), _s("也|yě|also"),
                   _s("们|men|plural_marker"), _s("田|tián|field")],
     "en": "Bright. Also. Plural marker. Field.",
     "qs": [{"q": "日 + 月 points toward…", "choices": ["明", "田", "们", "也"], "a": 0},
            {"q": "Which character means “also”?", "choices": ["也", "明", "田", "们"], "a": 0}]},
    {"id": "r0-8", "level": "R0", "title": "木 林 从 力 男", "title_en": "Wood, woods, from, strength, male",
     "intro": "Two 木 make 林, a small woods. 田 plus 力 gives 男, the old field-strength picture.",
     "new_words": [("木", "mù", "wood", [4]), ("林", "lín", "woods", [2]),
                   ("从", "cóng", "from", [2]), ("力", "lì", "strength", [4]),
                   ("男", "nán", "male", [2])],
     "sentences": [_s("木|mù|wood"), _s("林|lín|woods"), _s("从|cóng|from"),
                   _s("力|lì|strength"), _s("男|nán|male")],
     "en": "Wood. Woods. From. Strength. Male.",
     "qs": [{"q": "Two 木 suggest…", "choices": ["林", "男", "从", "力"], "a": 0},
            {"q": "田 + 力 points toward…", "choices": ["男", "林", "木", "从"], "a": 0}]},

    # ── R1 — characters make words ────────────────────────────────────────────
    {"id": "r1-1", "level": "R1", "title": "你好", "title_en": "Hello",
     "intro": "You + good = hello. Add 吗 and any statement becomes a question.",
     "note": "Reading tip: ？ is the question mark, just like in English — and in "
             "Chinese it usually arrives with a question word like 吗 at the end.",
     "new_words": [("你好", "nǐ hǎo", "hello", [3, 3]), ("吗", "ma", "question word", [5]),
                   ("很", "hěn", "very; is", [3])],
     "sentences": [_s("你好|nǐ_hǎo|hello 。"),
                   _s("你|nǐ|you 好|hǎo|good 吗|ma|question_word ？"),
                   _s("我|wǒ|I 很|hěn|very 好|hǎo|good 。")],
     "en": "Hello. How are you? I'm fine.",
     "qs": [{"q": "“你好吗？” is asking…", "choices": ["how you are", "your name", "where you live", "what you want"], "a": 0},
            {"q": "你 + 好 together mean…", "choices": ["hello", "goodbye", "thanks", "yes"], "a": 0}]},
    {"id": "r1-2", "level": "R1", "title": "妈妈 爸爸", "title_en": "Mom and dad",
     "intro": "Doubling a character makes it warm: 妈妈, 爸爸. With family, 我妈妈 is simply “my mom.”",
     "new_words": [("妈妈", "mā ma", "mom", [1, 5]), ("爸爸", "bà ba", "dad", [4, 5])],
     "sentences": [_s("妈妈|mā_ma|mom 。"), _s("爸爸|bà_ba|dad 。"),
                   _s("我|wǒ|my 妈妈|mā_ma|mom 很|hěn|very 好|hǎo|good 。"),
                   _s("你|nǐ|your 爸爸|bà_ba|dad 好|hǎo|good 吗|ma|question_word ？")],
     "en": "Mom. Dad. My mom is well. Is your dad well?",
     "qs": [{"q": "我妈妈 means…", "choices": ["my mom", "your mom", "his mom", "a mom"], "a": 0},
            {"q": "The last line asks about…", "choices": ["your dad", "my dad", "your mom", "the weather"], "a": 0}]},
    {"id": "r1-3", "level": "R1", "title": "大 + 山 = 大山", "title_en": "Characters combine",
     "intro": "This is the trick that makes reading Chinese possible: characters you know combine into words you can guess.",
     "new_words": [("大人", "dà rén", "adult, grown-up", [4, 2]),
                   ("山水", "shān shuǐ", "landscape, scenery", [1, 3])],
     "sentences": [_s("大|dà|big 山|shān|mountain 。"),
                   _s("小|xiǎo|small 山|shān|mountain 。"),
                   _s("大人|dà_rén|adult 。"),
                   _s("山水|shān_shuǐ|landscape 。")],
     "en": "Big mountain. Small mountain (a hill). Big-person (an adult). Mountain-water (a landscape).",
     "qs": [{"q": "大人 — big + person — means…", "choices": ["an adult", "a giant", "a crowd", "a boss"], "a": 0},
            {"q": "山水 literally “mountains and water” means…", "choices": ["scenery", "a flood", "a well", "an island"], "a": 0}]},
    {"id": "r1-4", "level": "R1", "title": "是 不 — yes and no", "title_en": "To be, or not",
     "intro": "是 links things: A 是 B. 不 in front says no. Together: 不是, is not.",
     "new_words": [("是", "shì", "to be", [4]), ("不", "bù", "not", [4])],
     "sentences": [_s("是|shì|is 。"), _s("不|bù|not 。"), _s("不是|bú_shì|is_not 。"),
                   _s("我|wǒ|I 是|shì|am 大人|dà_rén|adult 。"),
                   _s("他|tā|he 不是|bú_shì|is_not 大人|dà_rén|adult 。")],
     "en": "Is. Not. Is not. I am an adult. He is not an adult.",
     "qs": [{"q": "不是 means…", "choices": ["is not", "is", "maybe", "also"], "a": 0},
            {"q": "Who is NOT an adult here?", "choices": ["him", "me", "mom", "everyone is"], "a": 0}]},
    {"id": "r1-5", "level": "R1", "title": "日 + 月 = 明", "title_en": "Component magic",
     "intro": "Known pieces now make new words: sun plus moon gives bright; woman plus child gives good.",
     "new_words": [("天", "tiān", "day; sky", [1]), ("明天", "míng tiān", "tomorrow", [2, 1])],
     "sentences": [_s("日|rì|sun 月|yuè|moon 明|míng|bright 。"),
                   _s("天|tiān|sky 。"),
                   _s("明天|míng_tiān|tomorrow 。"),
                   _s("女|nǚ|woman 子|zǐ|child 好|hǎo|good 。")],
     "en": "Sun and moon: bright. Day. Tomorrow (bright-day). Woman and child: good.",
     "qs": [{"q": "日 plus 月 makes the idea…", "choices": ["bright", "small", "not", "horse"], "a": 0},
            {"q": "明天 means…", "choices": ["tomorrow", "today", "bright person", "moon"], "a": 0}]},
    {"id": "r1-6", "level": "R1", "title": "木 木 林", "title_en": "From wood to forest",
     "intro": "A repeated piece can grow the meaning: one 木, then 林, then 森林.",
     "new_words": [("森", "sēn", "dense trees", [1]), ("森林", "sēn lín", "forest", [1, 2])],
     "sentences": [_s("木|mù|wood 。"),
                   _s("林|lín|woods 。"),
                   _s("森|sēn|dense_trees 。"),
                   _s("森林|sēn_lín|forest 。")],
     "en": "Wood. Woods. Dense trees. Forest.",
     "qs": [{"q": "森林 means…", "choices": ["forest", "field", "person", "mouth"], "a": 0},
            {"q": "One 木, two 木, three 木 — the meaning grows with the…",
             "choices": ["number of pieces", "tone", "stroke order", "pinyin"], "a": 0}]},
    {"id": "r1-7", "level": "R1", "title": "我们 他们 她们", "title_en": "We and they",
     "intro": "Add 们 to people words and you get groups: we, they, they (women).",
     "new_words": [("我们", "wǒ men", "we, us", [3, 5]), ("他们", "tā men", "they, them", [1, 5]),
                   ("她们", "tā men", "they (women)", [1, 5])],
     "sentences": [_s("我们|wǒ_men|we 。"),
                   _s("他们|tā_men|they 。"),
                   _s("她们|tā_men|they_women 。"),
                   _s("我们|wǒ_men|we 也|yě|also 好|hǎo|good 。")],
     "en": "We. They. They (women). We are good too.",
     "qs": [{"q": "我们 means…", "choices": ["we", "they", "she", "also"], "a": 0},
            {"q": "Which character marks a group?", "choices": ["们", "我", "也", "好"], "a": 0}]},
    {"id": "r1-8", "level": "R1", "title": "男人 女人 田里", "title_en": "People in the field",
     "intro": "男 and 女 now join 人. Add 里 and a place can be inside something.",
     "new_words": [("男人", "nán rén", "man", [2, 2]), ("女人", "nǚ rén", "woman", [3, 2]),
                   ("里", "lǐ", "inside", [3]), ("田里", "tián lǐ", "in the field", [2, 3]),
                   ("和", "hé", "and", [2]), ("在", "zài", "at; in", [4])],
     "sentences": [_s("男人|nán_rén|man 。"),
                   _s("女人|nǚ_rén|woman 。"),
                   _s("里|lǐ|inside 。"),
                   _s("田里|tián_lǐ|in_the_field 。"),
                   _s("男人|nán_rén|man 和|hé|and 女人|nǚ_rén|woman 在|zài|at 田里|tián_lǐ|field 。")],
     "en": "Man. Woman. In the field. The man and woman are in the field.",
     "qs": [{"q": "男人 means…", "choices": ["man", "woman", "child", "teacher"], "a": 0},
            {"q": "田里 means…", "choices": ["in the field", "on the mountain", "inside the mouth", "tomorrow"], "a": 0}]},

    # ── R2 — first sentences ──────────────────────────────────────────────────
    {"id": "r2-1", "level": "R2", "title": "我是老师", "title_en": "Who is who",
     "intro": "Your first full sentences about people.",
     "new_words": [("老师", "lǎo shī", "teacher", [3, 1]), ("她", "tā", "she, her", [1]),
                   ("谁", "shéi", "who", [2])],
     "sentences": [_s("我|wǒ|I 是|shì|am 老师|lǎo_shī|teacher 。"),
                   _s("她|tā|she 是|shì|is 我|wǒ|my 妈妈|mā_ma|mom 。"),
                   _s("他|tā|he 是|shì|is 我|wǒ|my 爸爸|bà_ba|dad 。"),
                   _s("你|nǐ|you 是|shì|are 谁|shéi|who ？")],
     "en": "I am a teacher. She is my mom. He is my dad. Who are you?",
     "qs": [{"q": "What is the speaker's job?", "choices": ["teacher", "doctor", "shopkeeper", "student"], "a": 0},
            {"q": "谁 asks…", "choices": ["who", "what", "where", "when"], "a": 0}]},
    {"id": "r2-2", "level": "R2", "title": "我要喝茶", "title_en": "I want tea",
     "intro": "要 wants things; 喝 drinks them.",
     "new_words": [("要", "yào", "to want", [4]), ("喝", "hē", "to drink", [1]),
                   ("茶", "chá", "tea", [2]), ("咖啡", "kā fēi", "coffee", [1, 1])],
     "sentences": [_s("我|wǒ|I 要|yào|want 喝|hē|drink 茶|chá|tea 。"),
                   _s("妈妈|mā_ma|mom 要|yào|wants 喝|hē|drink 咖啡|kā_fēi|coffee 。"),
                   _s("你|nǐ|you 要|yào|want 喝|hē|drink 水|shuǐ|water 吗|ma|question_word ？")],
     "en": "I want to drink tea. Mom wants to drink coffee. Do you want to drink water?",
     "qs": [{"q": "What does mom want?", "choices": ["coffee", "tea", "water", "nothing"], "a": 0},
            {"q": "The last sentence is…", "choices": ["a question", "a statement", "a story", "a name"], "a": 0}]},
    {"id": "r2-3", "level": "R2", "title": "我家有猫", "title_en": "My family",
     "intro": "有 means to have — and families are counted in 口, mouths.",
     "note": "Reading tip: 、 is the listing comma — it separates items in a list "
             "(爸爸、妈妈和我). The ordinary comma ， separates phrases.",
     "new_words": [("家", "jiā", "home, family", [1]), ("有", "yǒu", "to have", [3]),
                   ("猫", "māo", "cat", [1]), ("和", "hé", "and", [2])],
     "sentences": [_s("我|wǒ|my 家|jiā|family 有|yǒu|has 三|sān|three 口|kǒu|mouths_(family_measure) 人|rén|people 。"),
                   _s("爸爸|bà_ba|dad 、 妈妈|mā_ma|mom 和|hé|and 我|wǒ|me 。"),
                   _s("我|wǒ|my 家|jiā|family 有|yǒu|has 猫|māo|cat 。"),
                   _s("猫|māo|cat 很|hěn|very 小|xiǎo|small 。")],
     "en": "My family has three people. Dad, mom and me. My family has a cat. The cat is very small.",
     "qs": [{"q": "How many people are in the family?", "choices": ["three", "two", "four", "ten"], "a": 0},
            {"q": "What is small?", "choices": ["the cat", "the house", "dad", "the tea"], "a": 0}]},
    {"id": "r2-4", "level": "R2", "title": "你喜欢什么？", "title_en": "What do you like?",
     "intro": "喜欢 likes things — or whole activities.",
     "new_words": [("喜欢", "xǐ huan", "to like", [3, 5]), ("什么", "shén me", "what", [2, 5]),
                   ("吃", "chī", "to eat", [1]), ("米饭", "mǐ fàn", "cooked rice", [3, 4])],
     "sentences": [_s("我|wǒ|I 喜欢|xǐ_huan|like 喝|hē|drink 茶|chá|tea 。"),
                   _s("妈妈|mā_ma|mom 喜欢|xǐ_huan|likes 吃|chī|eat 米饭|mǐ_fàn|rice 。"),
                   _s("猫|māo|cat 不|bù|not 喜欢|xǐ_huan|like 米饭|mǐ_fàn|rice 。"),
                   _s("你|nǐ|you 喜欢|xǐ_huan|like 什么|shén_me|what ？")],
     "en": "I like drinking tea. Mom likes eating rice. The cat doesn't like rice. What do you like?",
     "qs": [{"q": "Who likes rice?", "choices": ["mom", "the cat", "the speaker", "dad"], "a": 0},
            {"q": "什么 means…", "choices": ["what", "who", "cat", "like"], "a": 0}]},
    {"id": "r2-5", "level": "R2", "title": "我去商店", "title_en": "To the shop",
     "intro": "去 goes places; 买 buys things — with 钱.",
     "new_words": [("去", "qù", "to go", [4]), ("商店", "shāng diàn", "shop", [1, 4]),
                   ("买", "mǎi", "to buy", [3]), ("钱", "qián", "money", [2])],
     "sentences": [_s("我|wǒ|I 去|qù|go 商店|shāng_diàn|shop 。"),
                   _s("我|wǒ|I 要|yào|want 买|mǎi|buy 茶|chá|tea 。"),
                   _s("我|wǒ|I 有|yǒu|have 钱|qián|money 。"),
                   _s("爸爸|bà_ba|dad 不|bú|not 去|qù|go 。")],
     "en": "I go to the shop. I want to buy tea. I have money. Dad isn't going.",
     "qs": [{"q": "What will the speaker buy?", "choices": ["tea", "rice", "coffee", "a cat"], "a": 0},
            {"q": "Who stays home?", "choices": ["dad", "mom", "the speaker", "the cat"], "a": 0}]},
    {"id": "r2-6", "level": "R2", "title": "几点起床？", "title_en": "What time do you get up?",
     "intro": "Time words unlock a day: 几 asks the number, 点 is o'clock, 半 is half past.",
     "new_words": [("几", "jǐ", "how many", [3]), ("点", "diǎn", "o'clock", [3]),
                   ("半", "bàn", "half", [4]), ("起床", "qǐ chuáng", "to get up", [3, 2]),
                   ("早上", "zǎo shang", "morning", [3, 5])],
     "sentences": [_s("你|nǐ|you 几|jǐ|what_number 点|diǎn|o'clock 起床|qǐ_chuáng|get_up ？"),
                   _s("我|wǒ|I 早上|zǎo_shang|morning 六|liù|six 点|diǎn|o'clock 半|bàn|half 起床|qǐ_chuáng|get_up 。"),
                   _s("妈妈|mā_ma|mom 早上|zǎo_shang|morning 七|qī|seven 点|diǎn|o'clock 起床|qǐ_chuáng|get_up 。")],
     "en": "What time do you get up? I get up at half past six in the morning. Mom gets up at seven.",
     "qs": [{"q": "When does the speaker get up?", "choices": ["6:30", "7:00", "9:00", "10:30"], "a": 0},
            {"q": "半 means…", "choices": ["half", "morning", "how many", "sleep"], "a": 0}]},
    {"id": "r2-7", "level": "R2", "title": "这个 那个", "title_en": "This one, that one",
     "intro": "这 and 那 point; 个 lets them point at a thing.",
     "new_words": [("这", "zhè", "this", [4]), ("那", "nà", "that", [4]),
                   ("个", "gè", "general measure word", [4]), ("东西", "dōng xi", "thing", [1, 5]),
                   ("书", "shū", "book", [1]), ("的", "de", "'s; mine", [5])],
     "sentences": [_s("这|zhè|this 个|gè|one 东西|dōng_xi|thing 很|hěn|very 好|hǎo|good 。"),
                   _s("那|nà|that 个|gè|one 东西|dōng_xi|thing 很|hěn|very 大|dà|big 。"),
                   _s("这|zhè|this 个|gè|one 书|shū|book 是|shì|is 我|wǒ|my 的|de|'s 。")],
     "en": "This thing is good. That thing is big. This book is mine.",
     "qs": [{"q": "这 points to…", "choices": ["this", "that", "where", "who"], "a": 0},
            {"q": "What belongs to the speaker?", "choices": ["this book", "that thing", "the shop", "the cat"], "a": 0}]},
    {"id": "r2-8", "level": "R2", "title": "我在学校", "title_en": "At school",
     "intro": "School words share 学: learn, student, school, classmate.",
     "new_words": [("学校", "xué xiào", "school", [2, 4]), ("学生", "xué sheng", "student", [2, 5]),
                   ("同学", "tóng xué", "classmate", [2, 2]), ("中文", "zhōng wén", "Chinese language", [1, 2])],
     "sentences": [_s("我|wǒ|I 在|zài|at 学校|xué_xiào|school 。"),
                   _s("我|wǒ|I 是|shì|am 学生|xué_sheng|student 。"),
                   _s("老师|lǎo_shī|teacher 和|hé|and 同学|tóng_xué|classmate 在|zài|at 学校|xué_xiào|school 。"),
                   _s("我们|wǒ_men|we 学|xué|learn 中文|zhōng_wén|Chinese 。")],
     "en": "I am at school. I am a student. The teacher and classmates are at school. We study Chinese.",
     "qs": [{"q": "Where is the speaker?", "choices": ["at school", "at the shop", "at home", "on a mountain"], "a": 0},
            {"q": "What do they study?", "choices": ["Chinese", "math", "English", "music"], "a": 0}]},
    {"id": "r2-9", "level": "R2", "title": "红花 白云 黑狗", "title_en": "Colors outside",
     "intro": "Color words sit before the thing they describe: red flower, white cloud, black dog.",
     "new_words": [("红", "hóng", "red", [2]), ("白", "bái", "white", [2]),
                   ("黑", "hēi", "black", [1]), ("花", "huā", "flower", [1]),
                   ("云", "yún", "cloud", [2]), ("狗", "gǒu", "dog", [3]),
                   ("看", "kàn", "to look at", [4])],
     "sentences": [_s("红|hóng|red 花|huā|flower 。"),
                   _s("白|bái|white 云|yún|cloud 。"),
                   _s("黑|hēi|black 狗|gǒu|dog 。"),
                   _s("我|wǒ|I 看|kàn|look_at 红|hóng|red 花|huā|flower 和|hé|and 白|bái|white 云|yún|cloud 。")],
     "en": "Red flower. White cloud. Black dog. I look at the red flowers and white clouds.",
     "qs": [{"q": "What color is the flower?", "choices": ["red", "white", "black", "green"], "a": 0},
            {"q": "What is black?", "choices": ["the dog", "the cloud", "the flower", "the book"], "a": 0}]},
    {"id": "r2-10", "level": "R2", "title": "电话号码", "title_en": "A phone number",
     "intro": "Numbers come back as phone numbers. 零 is zero, and 号 is number.",
     "new_words": [("电话", "diàn huà", "telephone", [4, 4]), ("号", "hào", "number", [4]),
                   ("零", "líng", "zero", [2]), ("呢", "ne", "and…?", [5]),
                   ("听", "tīng", "to listen", [1])],
     "sentences": [_s("我|wǒ|my 电话|diàn_huà|phone 号|hào|number 是|shì|is 六|liù|six 七|qī|seven 九|jiǔ|nine 零|líng|zero 八|bā|eight 。"),
                   _s("你|nǐ|your 电话|diàn_huà|phone 号|hào|number 呢|ne|and ？"),
                   _s("我|wǒ|I 听|tīng|listen 。 好|hǎo|okay ， 六|liù|six 七|qī|seven 九|jiǔ|nine 零|líng|zero 八|bā|eight ！")],
     "en": "My phone number is 67908. What is your phone number? I'm listening. Okay — 67908!",
     "qs": [{"q": "What is the speaker's phone number?", "choices": ["67908", "67980", "96708", "679"], "a": 0},
            {"q": "零 means…", "choices": ["zero", "number", "phone", "listen"], "a": 0}]},

    # ── R3 — dialogues ────────────────────────────────────────────────────────
    {"id": "r3-1", "level": "R3", "title": "在茶店", "title_en": "At the tea shop",
     "intro": "Your first conversation — buying tea, start to finish. The prices "
              "put your R0 numbers to work.",
     "note": "Reading tip: ！ is the exclamation mark, and dialogue lines are "
             "labeled with the speaker's name — tap a name to hear it.",
     "new_words": [("杯", "bēi", "cup (measure word)", [1]), ("多少", "duō shao", "how much", [1, 5]),
                   ("块", "kuài", "yuan (money)", [4]), ("老板", "lǎo bǎn", "shopkeeper, boss", [3, 3]),
                   ("谢谢", "xiè xie", "thanks", [4, 5])],
     "sentences": [_s("你好|nǐ_hǎo|hello ！ 我|wǒ|I 要|yào|want 一|yì|one 杯|bēi|cup 茶|chá|tea 。 多少|duō_shao|how_much 钱|qián|money ？", "安娜"),
                   _s("大|dà|big 杯|bēi|cup 十|shí|ten 块|kuài|yuan ， 小|xiǎo|small 杯|bēi|cup 五|wǔ|five 块|kuài|yuan 。", "老板"),
                   _s("要|yào|want 大|dà|big 杯|bēi|cup 。", "安娜"),
                   _s("好|hǎo|okay ！ 十|shí|ten 块|kuài|yuan 。", "老板"),
                   _s("谢谢|xiè_xie|thanks ！", "安娜")],
     "en": "Anna: Hello! I want a cup of tea. How much? — Shopkeeper: A large cup is ten yuan, a small one is five. — Anna: The large one, please. — Shopkeeper: Okay! Ten yuan. — Anna: Thanks!",
     "qs": [{"q": "What size does Anna choose?", "choices": ["large", "small", "medium", "none"], "a": 0},
            {"q": "How much does she pay?", "choices": ["10 yuan", "5 yuan", "3 yuan", "15 yuan"], "a": 0}]},
    {"id": "r3-2", "level": "R3", "title": "明天见", "title_en": "See you tomorrow",
     "intro": "Two friends run into each other. 呢 bounces a question back; 也 says “me too.”",
     "new_words": [("明天", "míng tiān", "tomorrow", [2, 1]), ("见", "jiàn", "to see, to meet", [4]),
                   ("再见", "zài jiàn", "goodbye", [4, 4]), ("呢", "ne", "and…? (bounce-back)", [5]),
                   ("也", "yě", "also", [3])],
     "sentences": [_s("你好|nǐ_hǎo|hello ， 安娜|Ān_nà|Anna ！ 你|nǐ|you 好|hǎo|well 吗|ma|question_word ？", "王明"),
                   _s("我|wǒ|I 很|hěn|very 好|hǎo|well ！ 你|nǐ|you 呢|ne|and_you ？", "安娜"),
                   _s("我|wǒ|I 也|yě|also 很|hěn|very 好|hǎo|well 。", "王明"),
                   _s("我|wǒ|I 去|qù|go 商店|shāng_diàn|shop 买|mǎi|buy 茶|chá|tea 。 明天|míng_tiān|tomorrow 见|jiàn|see ！", "安娜"),
                   _s("好|hǎo|okay ， 明天|míng_tiān|tomorrow 见|jiàn|see ！ 再见|zài_jiàn|goodbye ！", "王明")],
     "en": "Wang Ming: Hello, Anna! How are you? — Anna: I'm great! And you? — Wang Ming: I'm great too. — Anna: I'm off to the shop to buy tea. See you tomorrow! — Wang Ming: Okay, see you tomorrow! Bye!",
     "qs": [{"q": "Where is Anna going?", "choices": ["to the shop", "home", "to school", "to the mountain"], "a": 0},
            {"q": "When will they meet?", "choices": ["tomorrow", "today", "next week", "never"], "a": 0}]},
    {"id": "r3-3", "level": "R3", "title": "你家有几口人？", "title_en": "How many in your family?",
     "intro": "几 asks “how many” for small numbers — and 两, not 二, counts pairs of things.",
     "new_words": [("几", "jǐ", "how many", [3]),
                   ("妹妹", "mèi mei", "little sister", [4, 5]), ("两", "liǎng", "two (of something)", [3]),
                   ("只", "zhī", "(measure for animals)", [1])],
     "sentences": [_s("你|nǐ|your 家|jiā|family 有|yǒu|has 几|jǐ|how_many 口|kǒu|mouths 人|rén|people ？", "王明"),
                   _s("四|sì|four 口|kǒu|mouths 人|rén|people ： 爸爸|bà_ba|dad 、 妈妈|mā_ma|mom 、 我|wǒ|me 和|hé|and 我|wǒ|my 妹妹|mèi_mei|little_sister 。", "安娜"),
                   _s("你|nǐ|your 家|jiā|family 有|yǒu|has 猫|māo|cat 吗|ma|question_word ？", "王明"),
                   _s("有|yǒu|have ！ 我|wǒ|my 家|jiā|family 有|yǒu|has 两|liǎng|two 只|zhī|(measure) 猫|māo|cats 。", "安娜")],
     "en": "Wang Ming: How many people are in your family? — Anna: Four: dad, mom, me and my little sister. — Wang Ming: Does your family have a cat? — Anna: We do! We have two cats.",
     "qs": [{"q": "How many people are in Anna's family?", "choices": ["four", "three", "two", "five"], "a": 0},
            {"q": "How many cats?", "choices": ["two", "one", "four", "none"], "a": 0}]},
    {"id": "r3-4", "level": "R3", "title": "妹妹六岁", "title_en": "Little sister is six",
     "intro": "Ages make the number characters useful again. 问 means to ask.",
     "new_words": [("岁", "suì", "years old", [4]), ("问", "wèn", "to ask", [4]),
                   ("姐姐", "jiě jie", "older sister", [3, 5])],
     "sentences": [_s("王明|Wáng_Míng|Wang_Ming 问|wèn|asks ： 你|nǐ|your 妹妹|mèi_mei|little_sister 几|jǐ|how_many 岁|suì|years_old ？", "王明"),
                   _s("她|tā|she 六|liù|six 岁|suì|years_old 。", "安娜"),
                   _s("你|nǐ|you 是|shì|are 姐姐|jiě_jie|older_sister 吗|ma|question_word ？", "王明"),
                   _s("是|shì|yes 。 我|wǒ|I 是|shì|am 姐姐|jiě_jie|older_sister 。", "安娜")],
     "en": "Wang Ming asks: How old is your little sister? — She is six. — Are you the older sister? — Yes. I am the older sister.",
     "qs": [{"q": "How old is the little sister?", "choices": ["six", "seven", "nine", "ten"], "a": 0},
            {"q": "问 means…", "choices": ["to ask", "to buy", "to drink", "to sit"], "a": 0}]},
    {"id": "r3-5", "level": "R3", "title": "你去哪儿？", "title_en": "Where are you going?",
     "intro": "Directions start with 哪儿, where, then grow into left, right, and walking.",
     "new_words": [("哪儿", "nǎr", "where", [3]), ("走", "zǒu", "to walk", [3]),
                   ("往", "wǎng", "toward", [3]), ("左", "zuǒ", "left", [3]),
                   ("右", "yòu", "right", [4])],
     "sentences": [_s("你|nǐ|you 去|qù|go 哪儿|nǎr|where ？", "安娜"),
                   _s("我|wǒ|I 去|qù|go 学校|xué_xiào|school 。", "王明"),
                   _s("学校|xué_xiào|school 在|zài|at 哪儿|nǎr|where ？", "安娜"),
                   _s("往|wǎng|toward 左|zuǒ|left 走|zǒu|walk ， 再|zài|again 往|wǎng|toward 右|yòu|right 走|zǒu|walk 。", "王明")],
     "en": "Anna: Where are you going? — Wang Ming: I'm going to school. — Anna: Where is the school? — Wang Ming: Walk left, then walk right.",
     "qs": [{"q": "Where is Wang Ming going?", "choices": ["school", "the shop", "home", "the restaurant"], "a": 0},
            {"q": "Which direction comes first?", "choices": ["left", "right", "straight", "back"], "a": 0}]},
    {"id": "r3-6", "level": "R3", "title": "房间里", "title_en": "In the room",
     "intro": "A small room scene: door, table, chair, and the inside word you already know.",
     "new_words": [("房间", "fáng jiān", "room", [2, 1]), ("桌子", "zhuō zi", "table", [1, 5]),
                   ("椅子", "yǐ zi", "chair", [3, 5]), ("门", "mén", "door", [2])],
     "sentences": [_s("我|wǒ|my 房间|fáng_jiān|room 很|hěn|very 小|xiǎo|small 。"),
                   _s("房间|fáng_jiān|room 里|lǐ|inside 有|yǒu|has 桌子|zhuō_zi|table 和|hé|and 椅子|yǐ_zi|chair 。"),
                   _s("门|mén|door 不|bù|not 大|dà|big 。"),
                   _s("小|xiǎo|small 狗|gǒu|dog 在|zài|at 门|mén|door 里|lǐ|inside 。")],
     "en": "My room is small. In the room there is a table and chair. The door is not big. The little dog is inside the door.",
     "qs": [{"q": "What is in the room?", "choices": ["a table and chair", "two cats", "tea and coffee", "a phone"], "a": 0},
            {"q": "Where is the dog?", "choices": ["inside the door", "at school", "in the shop", "on the mountain"], "a": 0}]},
    {"id": "r3-7", "level": "R3", "title": "在饭馆", "title_en": "At the restaurant",
     "intro": "Ordering grows from 要: noodles, milk, dishes, and whether something tastes good.",
     "new_words": [("饭馆", "fàn guǎn", "restaurant", [4, 3]), ("面条", "miàn tiáo", "noodles", [4, 2]),
                   ("牛奶", "niú nǎi", "milk", [2, 3]), ("菜", "cài", "dish; vegetable", [4]),
                   ("好吃", "hǎo chī", "tasty", [3, 1])],
     "sentences": [_s("我们|wǒ_men|we 在|zài|at 饭馆|fàn_guǎn|restaurant 。", "安娜"),
                   _s("我|wǒ|I 要|yào|want 面条|miàn_tiáo|noodles 。", "王明"),
                   _s("我|wǒ|I 要|yào|want 牛奶|niú_nǎi|milk 。", "安娜"),
                   _s("这个|zhè_ge|this 菜|cài|dish 很|hěn|very 好吃|hǎo_chī|tasty ！", "王明")],
     "en": "Anna: We're at the restaurant. — Wang Ming: I want noodles. — Anna: I want milk. — Wang Ming: This dish is tasty!",
     "qs": [{"q": "What does Wang Ming want?", "choices": ["noodles", "milk", "coffee", "rice"], "a": 0},
            {"q": "How is the dish?", "choices": ["tasty", "too expensive", "cold", "small"], "a": 0}]},
    {"id": "r3-8", "level": "R3", "title": "这件衣服", "title_en": "This piece of clothing",
     "intro": "Shopping now has a measure word for clothes: 件.",
     "new_words": [("衣服", "yī fu", "clothes", [1, 5]), ("件", "jiàn", "measure for clothes", [4]),
                   ("漂亮", "piào liang", "pretty", [4, 5]), ("新", "xīn", "new", [1])],
     "sentences": [_s("这|zhè|this 件|jiàn|piece 衣服|yī_fu|clothes 很|hěn|very 漂亮|piào_liang|pretty 。", "安娜"),
                   _s("那|nà|that 件|jiàn|piece 衣服|yī_fu|clothes 也|yě|also 很|hěn|very 新|xīn|new 。", "王明"),
                   _s("多少|duō_shao|how_much 钱|qián|money ？", "安娜"),
                   _s("九|jiǔ|nine 十|shí|ten 块|kuài|yuan 。", "王明")],
     "en": "Anna: This piece of clothing is pretty. — Wang Ming: That one is new too. — Anna: How much? — Wang Ming: Ninety yuan.",
     "qs": [{"q": "Which measure word appears with clothing?", "choices": ["件", "杯", "只", "口"], "a": 0},
            {"q": "How much is it?", "choices": ["90 yuan", "9 yuan", "10 yuan", "7 yuan"], "a": 0}]},
    {"id": "r3-9", "level": "R3", "title": "昨天和今天", "title_en": "Yesterday and today",
     "intro": "Time words now tell a tiny day story: yesterday, today, work, busy, tired.",
     "new_words": [("昨天", "zuó tiān", "yesterday", [2, 1]), ("今天", "jīn tiān", "today", [1, 1]),
                   ("工作", "gōng zuò", "work", [1, 4]), ("忙", "máng", "busy", [2]),
                   ("累", "lèi", "tired", [4])],
     "sentences": [_s("昨天|zuó_tiān|yesterday 我|wǒ|I 工作|gōng_zuò|worked 。"),
                   _s("我|wǒ|I 很|hěn|very 忙|máng|busy ， 也|yě|also 很|hěn|very 累|lèi|tired 。"),
                   _s("今天|jīn_tiān|today 我|wǒ|I 不|bù|not 工作|gōng_zuò|work 。"),
                   _s("今天|jīn_tiān|today 我|wǒ|I 在|zài|at 家|jiā|home 看|kàn|read 书|shū|book 。")],
     "en": "Yesterday I worked. I was busy and tired. Today I don't work. Today I read at home.",
     "qs": [{"q": "How did the speaker feel yesterday?", "choices": ["busy and tired", "cold", "hungry", "lost"], "a": 0},
            {"q": "What happens today?", "choices": ["no work", "school starts", "a birthday", "buying clothes"], "a": 0}]},
    {"id": "r3-10", "level": "R3", "title": "天气冷不冷？", "title_en": "Is the weather cold?",
     "intro": "Weather words let a dialogue open with real daily small talk.",
     "new_words": [("天气", "tiān qì", "weather", [1, 4]), ("冷", "lěng", "cold", [3]),
                   ("热", "rè", "hot", [4]), ("下雨", "xià yǔ", "to rain", [4, 3])],
     "sentences": [_s("今天|jīn_tiān|today 天气|tiān_qì|weather 冷|lěng|cold 不|bù|not 冷|lěng|cold ？", "王明"),
                   _s("不|bù|not 冷|lěng|cold ， 也|yě|also 不|bù|not 热|rè|hot 。", "安娜"),
                   _s("明天|míng_tiān|tomorrow 下雨|xià_yǔ|rain 吗|ma|question_word ？", "王明"),
                   _s("明天|míng_tiān|tomorrow 不|bù|not 下雨|xià_yǔ|rain 。", "安娜")],
     "en": "Wang Ming: Is the weather cold today? — Anna: Not cold, and not hot. — Wang Ming: Will it rain tomorrow? — Anna: It won't rain tomorrow.",
     "qs": [{"q": "How is today's weather?", "choices": ["not cold and not hot", "very cold", "very hot", "rainy"], "a": 0},
            {"q": "What about tomorrow?", "choices": ["it will not rain", "it will snow", "it will be hot", "it will rain"], "a": 0}]},
    {"id": "r3-11", "level": "R3", "title": "从田里到森林", "title_en": "From the field to the forest",
     "intro": "A little walk that brings the early component words back inside "
              "real sentences — field, forest, and everyone you've met.",
     "new_words": [("来", "lái", "to come", [2]),
                   ("有力", "yǒu lì", "strong, powerful", [3, 4])],
     "sentences": [_s("今天|jīn_tiān|today 天气|tiān_qì|weather 很|hěn|very 好|hǎo|good ， 不|bù|not 冷|lěng|cold ， 也|yě|also 不|bú|not 热|rè|hot 。"),
                   _s("男人|nán_rén|man 和|hé|and 两|liǎng|two 个|gè|(measure) 女人|nǚ_rén|women 从|cóng|from 田里|tián_lǐ|the_field 走|zǒu|walk 。"),
                   _s("他们|tā_men|they 去|qù|go_to 森林|sēn_lín|forest 。"),
                   _s("男人|nán_rén|man 很|hěn|very 有力|yǒu_lì|strong 。"),
                   _s("她们|tā_men|they_(the_women) 看|kàn|look_at 白|bái|white 云|yún|clouds 。"),
                   _s("森林|sēn_lín|forest 很|hěn|very 大|dà|big ， 田|tián|field 很|hěn|very 小|xiǎo|small 。"),
                   _s("黑|hēi|black 狗|gǒu|dog 也|yě|also 来|lái|comes 。"),
                   _s("狗|gǒu|dog 看|kàn|looks_at 红|hóng|red 花|huā|flowers 。")],
     "en": "The weather is lovely today — not cold, not hot. The man and two women walk from the field. They go to the forest. The man is strong. The women watch the white clouds. The forest is big; the field is small. The black dog comes too. The dog looks at the red flowers.",
     "qs": [{"q": "Where do the man and woman walk from?", "choices": ["the field", "the shop", "school", "home"], "a": 0},
            {"q": "Which is bigger?", "choices": ["the forest", "the field", "the dog", "the flower"], "a": 0},
            {"q": "Who comes along too?", "choices": ["the black dog", "a teacher", "the shopkeeper", "a cat"], "a": 0}]},

    # ── R4 — paragraphs ───────────────────────────────────────────────────────
    {"id": "r4-1", "level": "R4", "title": "今天天气很好", "title_en": "A fine day",
     "intro": "A whole little paragraph — notice 了 marking what got done.",
     "new_words": [("今天", "jīn tiān", "today", [1, 1]), ("天气", "tiān qì", "weather", [1, 4]),
                   ("热", "rè", "hot", [4]), ("冷", "lěng", "cold", [3]),
                   ("我们", "wǒ men", "we, us", [3, 5]), ("了", "le", "(done!)", [5]),
                   ("多", "duō", "many, much", [1])],
     "sentences": [_s("今天|jīn_tiān|today 天气|tiān_qì|weather 很|hěn|very 好|hǎo|good 。"),
                   _s("不|bú|not 热|rè|hot ， 不|bù|not 冷|lěng|cold 。"),
                   _s("我|wǒ|I 和|hé|and 妈妈|mā_ma|mom 去|qù|go 商店|shāng_diàn|shop 。"),
                   _s("我们|wǒ_men|we 买|mǎi|bought 了|le|(done) 很|hěn|very 多|duō|much 茶|chá|tea 。")],
     "en": "The weather is lovely today. Not hot, not cold. Mom and I go to the shop. We bought a lot of tea.",
     "qs": [{"q": "What's the weather like?", "choices": ["just right", "too hot", "too cold", "raining"], "a": 0},
            {"q": "What did they buy?", "choices": ["a lot of tea", "a little tea", "coffee", "rice"], "a": 0}]},
    {"id": "r4-2", "level": "R4", "title": "我的家", "title_en": "My family",
     "intro": "的 marks belonging — 我的家, my family. Meet everyone.",
     "new_words": [("的", "de", "'s (belonging)", [5]), ("医生", "yī shēng", "doctor", [1, 1]),
                   ("工作", "gōng zuò", "to work; job", [1, 4]), ("忙", "máng", "busy", [2]),
                   ("累", "lèi", "tired", [4]), ("每天", "měi tiān", "every day", [3, 1])],
     "sentences": [_s("我|wǒ|my 的|de|'s 家|jiā|family 有|yǒu|has 四|sì|four 口|kǒu|mouths 人|rén|people 。"),
                   _s("我|wǒ|my 妈妈|mā_ma|mom 是|shì|is 医生|yī_shēng|doctor 。"),
                   _s("她|tā|she 每天|měi_tiān|every_day 工作|gōng_zuò|works ， 很|hěn|very 忙|máng|busy ， 也|yě|also 很|hěn|very 累|lèi|tired 。"),
                   _s("我|wǒ|my 爸爸|bà_ba|dad 不是|bú_shì|is_not 医生|yī_shēng|doctor ， 他|tā|he 是|shì|is 老师|lǎo_shī|teacher 。"),
                   _s("我|wǒ|I 和|hé|and 妹妹|mèi_mei|little_sister 喜欢|xǐ_huan|like 我们|wǒ_men|our 的|de|'s 家|jiā|home 。")],
     "en": "My family has four people. My mom is a doctor. She works every day — very busy, and very tired too. My dad isn't a doctor; he's a teacher. My little sister and I love our home.",
     "qs": [{"q": "What is mom's job?", "choices": ["doctor", "teacher", "shopkeeper", "driver"], "a": 0},
            {"q": "How does mom feel?", "choices": ["busy and tired", "bored", "cold", "hungry"], "a": 0},
            {"q": "Who is a teacher?", "choices": ["dad", "mom", "the sister", "nobody"], "a": 0}]},
    {"id": "r4-3", "level": "R4", "title": "小猫要吃什么？", "title_en": "What does the kitten want?",
     "intro": "A tiny scene at home. 它 is “it” — for animals and things.",
     "note": "Reading tip: speech is quoted with ：“ … ” — a colon and double "
             "quotes, right where English would use a comma and quotes.",
     "new_words": [("它", "tā", "it", [1]), ("鱼", "yú", "fish", [2]),
                   ("给", "gěi", "to give", [3]), ("看", "kàn", "to look at", [4]),
                   ("说", "shuō", "to say, to speak", [1]), ("喵", "miāo", "meow", [1])],
     "sentences": [_s("我|wǒ|my 家|jiā|family 的|de|'s 小|xiǎo|little 猫|māo|cat 很|hěn|very 好|hǎo|nice 。"),
                   _s("它|tā|it 不|bù|not 吃|chī|eat 米饭|mǐ_fàn|rice 。"),
                   _s("我|wǒ|I 给|gěi|give 它|tā|it 鱼|yú|fish 。 一|yī|one 、 二|èr|two 、 三|sān|three ！"),
                   _s("它|tā|it 看|kàn|looks_at 我|wǒ|me ， 说|shuō|says ： “ 喵|miāo|meow ！ ”"),
                   _s("妈妈|mā_ma|mom 说|shuō|says ： 小|xiǎo|little 猫|māo|cat 很|hěn|really 喜欢|xǐ_huan|likes 你|nǐ|you ！")],
     "en": "Our little cat is lovely. It doesn't eat rice. I give it fish — one, two, three! It looks at me and says: “Meow!” Mom says: the kitten really likes you!",
     "qs": [{"q": "What won't the cat eat?", "choices": ["rice", "fish", "tea", "anything"], "a": 0},
            {"q": "How many fish does it get?", "choices": ["three", "one", "two", "none"], "a": 0}]},

    # ── R5 — short stories ────────────────────────────────────────────────────
    {"id": "r5-1", "level": "R5", "title": "小马找朋友", "title_en": "The little horse looks for a friend",
     "intro": "Your first story with a beginning, a middle, and an end.",
     "new_words": [("马", "mǎ", "horse", [3]), ("上", "shàng", "on, on top of", [4]),
                   ("找", "zhǎo", "to look for", [3]),
                   ("朋友", "péng you", "friend", [2, 5]), ("来", "lái", "to come", [2]),
                   ("没有", "méi yǒu", "to not have", [2, 3]), ("高兴", "gāo xìng", "happy", [1, 4]),
                   ("现在", "xiàn zài", "now", [4, 4])],
     "sentences": [_s("山|shān|mountain 上|shàng|on_top 有|yǒu|there_is 一|yì|one 只|zhī|(measure) 小|xiǎo|little 马|mǎ|horse 。"),
                   _s("小|xiǎo|little 马|mǎ|horse 没有|méi_yǒu|doesn't_have 朋友|péng_you|friend 。"),
                   _s("它|tā|it 去|qù|goes 找|zhǎo|look_for 朋友|péng_you|friend 。"),
                   _s("它|tā|it 看|kàn|looks_at 大|dà|big 山|shān|mountain ， 看|kàn|looks_at 山水|shān_shuǐ|scenery ， 不|bú|not 看|kàn|see 人|rén|anyone 。"),
                   _s("一|yì|one 只|zhī|(measure) 小|xiǎo|little 猫|māo|cat 来|lái|comes 了|le|(done) ， 说|shuō|says ： “ 你好|nǐ_hǎo|hello ！ 你|nǐ|you 要|yào|want 朋友|péng_you|friend 吗|ma|question_word ？ ”"),
                   _s("小|xiǎo|little 马|mǎ|horse 说|shuō|says ： “ 要|yào|yes_I_want ！ ”"),
                   _s("现在|xiàn_zài|now 小|xiǎo|little 马|mǎ|horse 有|yǒu|has 朋友|péng_you|friend 了|le|(done) ， 它|tā|it 很|hěn|very 高兴|gāo_xìng|happy 。")],
     "en": "On the mountain there lives a little horse. The little horse has no friends. It goes looking for one. It sees the big mountain, sees the scenery — but no one at all. A little cat comes along and says: “Hello! Do you want a friend?” The little horse says: “Yes!” Now the little horse has a friend, and it is very happy.",
     "qs": [{"q": "What is the little horse looking for?", "choices": ["a friend", "food", "water", "its mom"], "a": 0},
            {"q": "Who comes along?", "choices": ["a little cat", "a big horse", "a person", "a fish"], "a": 0},
            {"q": "How does the story end?", "choices": ["the horse is happy", "the horse is lost", "it rains", "the cat leaves"], "a": 0}]},
    {"id": "r5-2", "level": "R5", "title": "下雨了", "title_en": "It's raining",
     "intro": "A rainy day at home — and 吧, the gentle “let's.”",
     "new_words": [("下雨", "xià yǔ", "to rain", [4, 3]), ("在", "zài", "at; -ing", [4]),
                   ("书", "shū", "book", [1]), ("吧", "ba", "let's… (suggestion)", [5]),
                   ("天", "tiān", "day; sky", [1])],
     "sentences": [_s("今天|jīn_tiān|today 下雨|xià_yǔ|rains 了|le|(done) 。"),
                   _s("我们|wǒ_men|we 不|bú|not 去|qù|go 商店|shāng_diàn|shop 。"),
                   _s("我|wǒ|I 在|zài|at 家|jiā|home 看|kàn|read 书|shū|book 。"),
                   _s("妹妹|mèi_mei|little_sister 在|zài|is_-ing 看|kàn|watching 小|xiǎo|little 猫|māo|cat 。"),
                   _s("妈妈|mā_ma|mom 说|shuō|says ： “ 我们|wǒ_men|we 喝|hē|drink 茶|chá|tea 吧|ba|let's 。 ”"),
                   _s("爸爸|bà_ba|dad 说|shuō|says ： “ 好|hǎo|great ！ 我|wǒ|I 也|yě|also 要|yào|want 一|yì|one 杯|bēi|cup ！ ”"),
                   _s("下雨|xià_yǔ|rainy 天|tiān|day 也|yě|also 很|hěn|very 好|hǎo|good 。")],
     "en": "It's raining today. We're not going to the shop. I read a book at home. My little sister is watching the kitten. Mom says: “Let's have some tea.” Dad says: “Great! I want a cup too!” Rainy days are lovely too.",
     "qs": [{"q": "Why does no one go to the shop?", "choices": ["it's raining", "it's closed", "no money", "too far"], "a": 0},
            {"q": "What is the speaker doing?", "choices": ["reading a book", "watching the cat", "drinking coffee", "sleeping"], "a": 0},
            {"q": "The story's feeling is…", "choices": ["cozy", "scary", "sad", "angry"], "a": 0}]},

    # ── R6 — a full story ─────────────────────────────────────────────────────
    {"id": "r6-1", "level": "R6", "title": "安娜去中国", "title_en": "Anna goes to China",
     "intro": "Everything you've read comes together: a full story, three parts, no pinyin unless you ask.",
     "new_words": [("中国", "Zhōng guó", "China", [1, 2]), ("汉语", "Hàn yǔ", "Chinese language", [4, 3]),
                   ("想", "xiǎng", "to want to; to think", [3]), ("坐", "zuò", "to take (transport); to sit", [4]),
                   ("飞机", "fēi jī", "airplane", [1, 1]), ("新", "xīn", "new", [1]),
                   ("他们", "tā men", "they, them", [1, 5]), ("明年", "míng nián", "next year", [2, 2]),
                   ("还", "hái", "still; again", [2])],
     "sentences": [_s("安娜|Ān_nà|Anna 很|hěn|really 喜欢|xǐ_huan|likes 汉语|Hàn_yǔ|Chinese 。"),
                   _s("她|tā|she 每天|měi_tiān|every_day 看|kàn|reads 书|shū|books ， 每天|měi_tiān|every_day 说|shuō|speaks 汉语|Hàn_yǔ|Chinese 。"),
                   _s("她|tā|she 想|xiǎng|wants_to 去|qù|go 中国|Zhōng_guó|China 。"),
                   _s("二月|èr_yuè|February 八日|bā_rì|the_8th ， 她|tā|she 坐|zuò|takes 飞机|fēi_jī|airplane 去|qù|to 中国|Zhōng_guó|China 。"),
                   _s("中国|Zhōng_guó|China 很|hěn|very 大|dà|big ！ 天气|tiān_qì|weather 很|hěn|very 好|hǎo|good 。"),
                   _s("她|tā|she 去|qù|goes_to 商店|shāng_diàn|shop 买|mǎi|buy 茶|chá|tea ， 说|shuō|says ： “ 我|wǒ|I 要|yào|want 一|yì|one 杯|bēi|cup 茶|chá|tea ， 谢谢|xiè_xie|thanks ！ ”"),
                   _s("老板|lǎo_bǎn|shopkeeper 说|shuō|says ： “ 你|nǐ|your 的|de|'s 汉语|Hàn_yǔ|Chinese 很|hěn|very 好|hǎo|good ！ ”"),
                   _s("安娜|Ān_nà|Anna 很|hěn|very 高兴|gāo_xìng|happy 。"),
                   _s("在|zài|in 中国|Zhōng_guó|China ， 安娜|Ān_nà|Anna 有|yǒu|has 了|le|(done) 很|hěn|very 多|duō|many 新|xīn|new 朋友|péng_you|friends 。"),
                   _s("他们|tā_men|they 和|hé|with 她|tā|her 说|shuō|speak 汉语|Hàn_yǔ|Chinese ， 喝|hē|drink 茶|chá|tea ， 看|kàn|look_at 大|dà|big 山|shān|mountains 。"),
                   _s("安娜|Ān_nà|Anna 说|shuō|says ： “ 我|wǒ|I 很|hěn|really 喜欢|xǐ_huan|like 中国|Zhōng_guó|China ！ 明年|míng_nián|next_year 我|wǒ|I 还|hái|again 要|yào|will 来|lái|come ！ ”")],
     "en": "Anna really likes Chinese. Every day she reads, and every day she speaks Chinese. She wants to go to China. On February 8th, she takes a plane to China. China is huge! The weather is beautiful. She goes to a shop to buy tea and says: “One cup of tea please, thank you!” The shopkeeper says: “Your Chinese is really good!” Anna is delighted. In China, Anna makes many new friends. They speak Chinese with her, drink tea, and look at the big mountains. Anna says: “I love China! Next year I'm coming back!”",
     "qs": [{"q": "How does Anna get to China?", "choices": ["by plane", "by train", "by boat", "on foot"], "a": 0},
            {"q": "What does the shopkeeper praise?", "choices": ["her Chinese", "her hat", "her money", "her friend"], "a": 0},
            {"q": "What does Anna do with her new friends?", "choices": ["speak Chinese and drink tea", "play football", "watch movies", "go fishing"], "a": 0},
            {"q": "What does she promise at the end?", "choices": ["to come back next year", "to move to China", "to open a shop", "to buy a horse"], "a": 0}]},

    {"id": "r4-4", "level": "R4", "title": "我的一天", "title_en": "My day",
     "intro": "A connected paragraph about morning, study, evening, and sleep.",
     "new_words": [("早上", "zǎo shang", "morning", [3, 5]), ("晚上", "wǎn shang", "evening", [3, 5]),
                   ("睡觉", "shuì jiào", "to sleep", [4, 4]), ("学习", "xué xí", "to study", [2, 2]),
                   ("汉语", "Hàn yǔ", "Chinese language", [4, 3]), ("中午", "zhōng wǔ", "noon", [1, 3]),
                   ("都", "dōu", "all, both", [1])],
     "sentences": [_s("早上|zǎo_shang|morning 我|wǒ|I 学习|xué_xí|study 汉语|Hàn_yǔ|Chinese 。"),
                   _s("中午|zhōng_wǔ|noon 我|wǒ|I 吃|chī|eat 米饭|mǐ_fàn|rice ， 喝|hē|drink 茶|chá|tea 。"),
                   _s("晚上|wǎn_shang|evening 我|wǒ|I 看|kàn|read 书|shū|book 。"),
                   _s("我|wǒ|I 不|bù|not 晚|wǎn|late 睡觉|shuì_jiào|sleep 。"),
                   _s("每天|měi_tiān|every_day 我|wǒ|I 都|dōu|all 学习|xué_xí|study 汉语|Hàn_yǔ|Chinese 。")],
     "en": "In the morning I study Chinese. At noon I eat rice and drink tea. In the evening I read. I do not sleep late. Every day I study Chinese.",
     "qs": [{"q": "What does the speaker study?", "choices": ["Chinese", "math", "music", "English"], "a": 0},
            {"q": "When does the speaker read?", "choices": ["in the evening", "in the morning", "at noon", "never"], "a": 0},
            {"q": "Does the speaker sleep late?", "choices": ["no", "yes", "only on Sunday", "the text does not say"], "a": 0}]},
    {"id": "r4-5", "level": "R4", "title": "去图书馆", "title_en": "Going to the library",
     "intro": "A small errand with a route, a map, and a book to return.",
     "new_words": [("图书馆", "tú shū guǎn", "library", [2, 1, 3]), ("还书", "huán shū", "to return a book", [2, 1]),
                   ("路线", "lù xiàn", "route", [4, 4]), ("附近", "fù jìn", "nearby", [4, 4]),
                   ("地图", "dì tú", "map", [4, 2]), ("方便", "fāng biàn", "convenient", [1, 4])],
     "sentences": [_s("图书馆|tú_shū_guǎn|library 在|zài|at 学校|xué_xiào|school 附近|fù_jìn|nearby 。"),
                   _s("安娜|Ān_nà|Anna 要|yào|needs 还书|huán_shū|return_a_book 。"),
                   _s("她|tā|she 看|kàn|looks_at 地图|dì_tú|map 和|hé|and 路线|lù_xiàn|route 。"),
                   _s("这|zhè|this 个|gè|one 路线|lù_xiàn|route 很|hěn|very 方便|fāng_biàn|convenient 。"),
                   _s("她|tā|she 从|cóng|from 学校|xué_xiào|school 走|zǒu|walks 去|qù|to 图书馆|tú_shū_guǎn|library 。")],
     "en": "The library is near the school. Anna needs to return a book. She looks at the map and finds the route. This route is convenient. She walks from school to the library.",
     "qs": [{"q": "Where is the library?", "choices": ["near the school", "inside the shop", "far from home", "at the airport"], "a": 0},
            {"q": "What does Anna need to do?", "choices": ["return a book", "buy tea", "call home", "sleep"], "a": 0},
            {"q": "What helps her find the route?", "choices": ["a map", "a ticket", "a cake", "a phone number"], "a": 0}]},
    {"id": "r4-6", "level": "R4", "title": "生日以前", "title_en": "Before the birthday",
     "intro": "A family birthday scene with a cake, gift, and song.",
     "new_words": [("生日", "shēng rì", "birthday", [1, 4]), ("礼物", "lǐ wù", "gift", [3, 4]),
                   ("蛋糕", "dàn gāo", "cake", [4, 1]), ("快乐", "kuài lè", "happy", [4, 4]),
                   ("唱歌", "chàng gē", "to sing", [4, 1]), ("准备", "zhǔn bèi", "to prepare", [3, 4])],
     "sentences": [_s("妹妹|mèi_mei|little_sister 的|de|'s 生日|shēng_rì|birthday 是|shì|is 今天|jīn_tiān|today 。"),
                   _s("妈妈|mā_ma|mom 准备|zhǔn_bèi|prepares 蛋糕|dàn_gāo|cake 。"),
                   _s("爸爸|bà_ba|dad 买|mǎi|buys 礼物|lǐ_wù|gift 。"),
                   _s("我们|wǒ_men|we 给|gěi|give 妹妹|mèi_mei|little_sister 唱歌|chàng_gē|sing 。"),
                   _s("妹妹|mèi_mei|little_sister 很|hěn|very 快乐|kuài_lè|happy 。")],
     "en": "Little sister's birthday is coming. Mom prepares a cake. Dad buys a gift. We sing to little sister. She is very happy.",
     "qs": [{"q": "Who prepares the cake?", "choices": ["mom", "dad", "Anna", "the teacher"], "a": 0},
            {"q": "What does dad buy?", "choices": ["a gift", "tea", "a map", "a book"], "a": 0},
            {"q": "How does little sister feel?", "choices": ["happy", "busy", "cold", "worried"], "a": 0}]},
    {"id": "r4-7", "level": "R4", "title": "四个季节", "title_en": "Four seasons",
     "intro": "Weather now stretches across the year: spring, summer, autumn, winter.",
     "new_words": [("春天", "chūn tiān", "spring", [1, 1]), ("夏天", "xià tiān", "summer", [4, 1]),
                   ("秋天", "qiū tiān", "autumn", [1, 1]), ("冬天", "dōng tiān", "winter", [1, 1]),
                   ("刮风", "guā fēng", "windy", [1, 1]), ("下雪", "xià xuě", "to snow", [4, 3]),
                   ("太阳", "tài yáng", "sun", [4, 2]), ("常常", "cháng cháng", "often", [2, 2])],
     "sentences": [_s("春天|chūn_tiān|spring 天气|tiān_qì|weather 很|hěn|very 好|hǎo|good 。"),
                   _s("夏天|xià_tiān|summer 太阳|tài_yáng|sun 很|hěn|very 大|dà|big 。"),
                   _s("秋天|qiū_tiān|autumn 常常|cháng_cháng|often 刮风|guā_fēng|windy 。"),
                   _s("冬天|dōng_tiān|winter 下雪|xià_xuě|snow 。"),
                   _s("安娜|Ān_nà|Anna 喜欢|xǐ_huan|likes 春天|chūn_tiān|spring ， 也|yě|also 喜欢|xǐ_huan|likes 秋天|qiū_tiān|autumn 。")],
     "en": "Spring weather is nice. In summer the sun is strong. In autumn it is often windy. In winter it may snow. Anna likes spring and also likes autumn.",
     "qs": [{"q": "Which season may have snow?", "choices": ["winter", "summer", "spring", "autumn"], "a": 0},
            {"q": "What is summer like?", "choices": ["the sun is strong", "it snows", "it is always dark", "it is a birthday"], "a": 0},
            {"q": "Which seasons does Anna like?", "choices": ["spring and autumn", "summer and winter", "winter only", "all four equally"], "a": 0}]},
    {"id": "r4-8", "level": "R4", "title": "办公室会议", "title_en": "Office meeting",
     "intro": "A small work scene: late, worried, then relieved.",
     "new_words": [("办公室", "bàn gōng shì", "office", [4, 1, 4]), ("会议", "huì yì", "meeting", [4, 4]),
                   ("迟到", "chí dào", "to be late", [2, 4]), ("着急", "zháo jí", "anxious, in a hurry", [2, 2]),
                   ("放心", "fàng xīn", "to relax, be at ease", [4, 1]), ("结束", "jié shù", "to end", [2, 4]),
                   ("经理", "jīng lǐ", "manager", [1, 3]), ("以后", "yǐ hòu", "afterward", [3, 4])],
     "sentences": [_s("王明|Wáng_Míng|Wang_Ming 在|zài|at 办公室|bàn_gōng_shì|office 工作|gōng_zuò|works 。"),
                   _s("今天|jīn_tiān|today 有|yǒu|has 一个|yí_gè|one 会议|huì_yì|meeting 。"),
                   _s("他|tā|he 迟到|chí_dào|late 了|le|(done) ， 很|hěn|very 着急|zháo_jí|anxious 。"),
                   _s("经理|jīng_lǐ|manager 说|shuō|says ： “ 放心|fàng_xīn|relax ， 会议|huì_yì|meeting 不|bù|not 晚|wǎn|late 。 ”"),
                   _s("会议|huì_yì|meeting 结束|jié_shù|ends 以后|yǐ_hòu|afterward ， 王明|Wáng_Míng|Wang_Ming 去|qù|goes 喝|hē|drink 茶|chá|tea 。")],
     "en": "Wang Ming works in an office. There is a meeting today. He is almost late and feels anxious. The manager says, relax, the meeting has not started yet. After the meeting ends, Wang Ming goes to drink tea.",
     "qs": [{"q": "Why is Wang Ming anxious?", "choices": ["he is almost late", "he lost money", "he is sick", "he forgot a birthday"], "a": 0},
            {"q": "What does the manager tell him?", "choices": ["relax", "go home", "buy a map", "return a book"], "a": 0},
            {"q": "What does Wang Ming do after the meeting?", "choices": ["drink tea", "sleep", "sing", "take a plane"], "a": 0}]},

    {"id": "r5-3", "level": "R5", "title": "一个生日计划", "title_en": "A birthday plan",
     "intro": "A short story about planning a birthday without spoiling the surprise.",
     "new_words": [("计划", "jì huà", "plan", [4, 4]), ("邀请", "yāo qǐng", "to invite", [1, 3]),
                   ("以前", "yǐ qián", "before", [3, 2]), ("以后", "yǐ hòu", "afterward", [3, 4]),
                   ("一起", "yì qǐ", "together", [4, 3]), ("最", "zuì", "most", [4])],
     "sentences": [_s("妹妹|mèi_mei|little_sister 的|de|'s 生日|shēng_rì|birthday 以前|yǐ_qián|before ， 安娜|Ān_nà|Anna 有|yǒu|has 一个|yí_gè|one 计划|jì_huà|plan 。"),
                   _s("她|tā|she 邀请|yāo_qǐng|invites 朋友|péng_you|friends 来|lái|come 家|jiā|home 里|lǐ|inside 。"),
                   _s("妈妈|mā_ma|mom 准备|zhǔn_bèi|prepares 蛋糕|dàn_gāo|cake ， 爸爸|bà_ba|dad 准备|zhǔn_bèi|prepares 礼物|lǐ_wù|gift 。"),
                   _s("大家|dà_jiā|everyone 一起|yì_qǐ|together 唱歌|chàng_gē|sing 。"),
                   _s("生日|shēng_rì|birthday 以后|yǐ_hòu|afterward ， 妹妹|mèi_mei|little_sister 说|shuō|says ： “ 这是|zhè_shì|this_is 我|wǒ|my 最|zuì|most 快乐|kuài_lè|happy 的|de|'s 一天|yì_tiān|one_day 。 ”")],
     "en": "Before little sister's birthday, Anna has a plan. She invites friends to come home. Mom prepares the cake and dad prepares the gift. Everyone sings together. After the birthday, little sister says this is her happiest day.",
     "qs": [{"q": "What does Anna make?", "choices": ["a birthday plan", "a map", "a work report", "a train ticket"], "a": 0},
            {"q": "Who does Anna invite?", "choices": ["friends", "doctors", "drivers", "teachers only"], "a": 0},
            {"q": "What do they do together?", "choices": ["sing", "work overtime", "return books", "take a plane"], "a": 0}]},
    {"id": "r5-4", "level": "R5", "title": "图书馆的雨天", "title_en": "Rainy day at the library",
     "intro": "Rain changes the plan, but the library turns out to be a good place.",
     "new_words": [("安静", "ān jìng", "quiet", [1, 4]), ("舒服", "shū fu", "comfortable", [1, 5]),
                   ("资料", "zī liào", "materials; data", [1, 4]), ("复印", "fù yìn", "to copy", [4, 4]),
                   ("通知", "tōng zhī", "notice; to notify", [1, 1]), ("借书", "jiè shū", "to borrow books", [4, 1]),
                   ("门口", "mén kǒu", "entrance", [2, 3]), ("开", "kāi", "to open", [1]),
                   ("公园", "gōng yuán", "park", [1, 2])],
     "sentences": [_s("今天|jīn_tiān|today 下雨|xià_yǔ|rains ， 安娜|Ān_nà|Anna 不|bù|not 去|qù|go 公园|gōng_yuán|park 。"),
                   _s("她|tā|she 去|qù|goes 图书馆|tú_shū_guǎn|library 借书|jiè_shū|borrow_books 。"),
                   _s("图书馆|tú_shū_guǎn|library 很|hěn|very 安静|ān_jìng|quiet ， 也|yě|also 很|hěn|very 舒服|shū_fu|comfortable 。"),
                   _s("老师|lǎo_shī|teacher 要|yào|wants 资料|zī_liào|materials ， 安娜|Ān_nà|Anna 给|gěi|for 老师|lǎo_shī|teacher 复印|fù_yìn|copy 。"),
                   _s("门口|mén_kǒu|entrance 有|yǒu|has 通知|tōng_zhī|notice ： 明天|míng_tiān|tomorrow 图书馆|tú_shū_guǎn|library 早|zǎo|early 开|kāi|opens 。")],
     "en": "It rains today, so Anna does not go to the park. She goes to the library to borrow books. The library is quiet and comfortable. The teacher needs materials, and Anna helps copy them. At the entrance there is a notice: tomorrow the library opens early.",
     "qs": [{"q": "Why does Anna not go to the park?", "choices": ["it is raining", "she is sick", "she has no money", "the park is far"], "a": 0},
            {"q": "What does Anna help copy?", "choices": ["materials", "a map", "a birthday card", "a menu"], "a": 0},
            {"q": "What does the notice say?", "choices": ["the library opens early tomorrow", "the library is closed forever", "books are expensive", "rain is coming"], "a": 0}]},
    {"id": "r5-5", "level": "R5", "title": "第一天上班", "title_en": "First day at work",
     "intro": "A work story about a new company, a manager, and one clear task.",
     "new_words": [("公司", "gōng sī", "company", [1, 1]), ("经理", "jīng lǐ", "manager", [1, 3]),
                   ("同事", "tóng shì", "coworker", [2, 4]), ("任务", "rèn wu", "task", [4, 5]),
                   ("加班", "jiā bān", "to work overtime", [1, 1]), ("请假", "qǐng jià", "to ask for leave", [3, 4]),
                   ("努力", "nǔ lì", "hardworking", [3, 4]), ("认真", "rèn zhēn", "serious, careful", [4, 1]),
                   ("帮助", "bāng zhù", "to help", [1, 4])],
     "sentences": [_s("王明|Wáng_Míng|Wang_Ming 今天|jīn_tiān|today 去|qù|goes 新|xīn|new 公司|gōng_sī|company 上班|shàng_bān|work 。"),
                   _s("经理|jīng_lǐ|manager 给|gěi|gives 他|tā|him 一个|yí_gè|one 任务|rèn_wu|task 。"),
                   _s("一个|yí_gè|one 同事|tóng_shì|coworker 帮助|bāng_zhù|helps 他|tā|him 。"),
                   _s("王明|Wáng_Míng|Wang_Ming 很|hěn|very 认真|rèn_zhēn|serious ， 也|yě|also 很|hěn|very 努力|nǔ_lì|hardworking 。"),
                   _s("晚上|wǎn_shang|evening 他|tā|he 不|bù|not 加班|jiā_bān|work_overtime ， 也|yě|also 不|bù|not 请假|qǐng_jià|ask_for_leave 。")],
     "en": "Wang Ming goes to his new company today. The manager gives him a task. A coworker helps him. Wang Ming is careful and hardworking. In the evening he does not work overtime and does not ask for leave.",
     "qs": [{"q": "Where does Wang Ming go?", "choices": ["a new company", "a library", "a hospital", "an airport"], "a": 0},
            {"q": "Who gives him a task?", "choices": ["the manager", "his sister", "a shopkeeper", "a doctor"], "a": 0},
            {"q": "How does Wang Ming work?", "choices": ["carefully and hard", "slowly and angrily", "not at all", "only at night"], "a": 0}]},
    {"id": "r5-6", "level": "R5", "title": "旅行的选择", "title_en": "Choosing a trip",
     "intro": "Travel planning with an address, route, reservation, and departure.",
     "new_words": [("旅行", "lǚ xíng", "to travel; trip", [3, 2]), ("选择", "xuǎn zé", "to choose; choice", [3, 2]),
                   ("预定", "yù dìng", "to reserve", [4, 4]), ("地址", "dì zhǐ", "address", [4, 3]),
                   ("机场", "jī chǎng", "airport", [1, 3]), ("出发", "chū fā", "to set out", [1, 1]),
                   ("到达", "dào dá", "to arrive", [4, 2]), ("行李", "xíng li", "luggage", [2, 5]),
                   ("火车", "huǒ chē", "train", [3, 1]), ("飞机", "fēi jī", "airplane", [1, 1])],
     "sentences": [_s("安娜|Ān_nà|Anna 和|hé|and 王明|Wáng_Míng|Wang_Ming 要|yào|will 旅行|lǚ_xíng|travel 。"),
                   _s("他们|tā_men|they 有|yǒu|have 两个|liǎng_gè|two 选择|xuǎn_zé|choices ： 火车|huǒ_chē|train 和|hé|and 飞机|fēi_jī|plane 。"),
                   _s("安娜|Ān_nà|Anna 预定|yù_dìng|reserves 了|le|(done) 去|qù|to 机场|jī_chǎng|airport 的|de|'s 车|chē|car 。"),
                   _s("地址|dì_zhǐ|address 和|hé|and 路线|lù_xiàn|route 都|dōu|both 在|zài|on 地图|dì_tú|map 里|lǐ|inside 。"),
                   _s("他们|tā_men|they 早上|zǎo_shang|morning 出发|chū_fā|set_out ， 中午|zhōng_wǔ|noon 到达|dào_dá|arrive ， 行李|xíng_li|luggage 不|bù|not 多|duō|much 。")],
     "en": "Anna and Wang Ming plan to travel. They have two choices: train or plane. Anna reserves a car to the airport. The address and route are both on the phone. They set out in the morning and arrive at noon; they do not have much luggage.",
     "qs": [{"q": "What are the two travel choices?", "choices": ["train or plane", "bus or bicycle", "walk or run", "ship or horse"], "a": 0},
            {"q": "Where are the address and route?", "choices": ["on the phone", "in a book", "at the bank", "on a cake"], "a": 0},
            {"q": "When do they arrive?", "choices": ["at noon", "in the evening", "tomorrow night", "before breakfast"], "a": 0}]},

    {"id": "r6-2", "level": "R6", "title": "月亮下的生日", "title_en": "Birthday under the moon",
     "intro": "A longer birthday story under the moon and stars.",
     "new_words": [("月亮", "yuè liang", "moon", [4, 5]), ("星星", "xīng xing", "stars", [1, 5]),
                   ("故事", "gù shi", "story", [4, 5]), ("结果", "jié guǒ", "result", [2, 3]),
                   ("后来", "hòu lái", "later", [4, 2]), ("经验", "jīng yàn", "experience", [1, 4]),
                   ("相信", "xiāng xìn", "to believe", [1, 4]), ("讲", "jiǎng", "to tell", [3]),
                   ("真的", "zhēn de", "real; true", [1, 5]), ("这次", "zhè cì", "this time", [4, 4])],
     "sentences": [_s("生日|shēng_rì|birthday 晚上|wǎn_shang|evening ， 月亮|yuè_liang|moon 很|hěn|very 亮|liàng|bright ， 星星|xīng_xing|stars 也|yě|also 很|hěn|very 多|duō|many 。"),
                   _s("安娜|Ān_nà|Anna 给|gěi|gives 妹妹|mèi_mei|little_sister 讲|jiǎng|tells 一个|yí_gè|one 故事|gù_shi|story 。"),
                   _s("故事|gù_shi|story 里|lǐ|inside 有|yǒu|has 小|xiǎo|little 马|mǎ|horse 、 小|xiǎo|little 猫|māo|cat 和|hé|and 大|dà|big 山|shān|mountain 。"),
                   _s("妹妹|mèi_mei|little_sister 相信|xiāng_xìn|believes 这个|zhè_ge|this 故事|gù_shi|story 是|shì|is 真的|zhēn_de|real 。"),
                   _s("结果|jié_guǒ|result ， 大家|dà_jiā|everyone 都|dōu|all 很|hěn|very 快乐|kuài_lè|happy 。"),
                   _s("后来|hòu_lái|later ， 安娜|Ān_nà|Anna 说|shuō|says ： 这次|zhè_cì|this_time 生日|shēng_rì|birthday 是|shì|is 很好|hěn_hǎo|good 的|de|'s 经验|jīng_yàn|experience 。")],
     "en": "On the birthday evening, the moon is bright and there are many stars. Anna tells little sister a story. In the story there is a little horse, a little cat and a mountain. Little sister believes the story is real. In the end, everyone laughs. Later, Anna says this birthday was a good experience.",
     "qs": [{"q": "What does Anna tell?", "choices": ["a story", "a route", "a notice", "a price"], "a": 0},
            {"q": "What does little sister believe?", "choices": ["the story is real", "the moon is gone", "the cake is bad", "the cat can work"], "a": 0},
            {"q": "How does everyone react?", "choices": ["they laugh", "they cry", "they leave", "they sleep"], "a": 0}]},
    {"id": "r6-3", "level": "R6", "title": "城市里的新工作", "title_en": "New work in the city",
     "intro": "A connected work story about a city, traffic, and a goal.",
     "new_words": [("城市", "chéng shì", "city", [2, 4]), ("环境", "huán jìng", "environment", [2, 4]),
                   ("交通", "jiāo tōng", "traffic", [1, 1]), ("机会", "jī huì", "opportunity", [1, 4]),
                   ("目标", "mù biāo", "goal", [4, 1]), ("过程", "guò chéng", "process", [4, 2]),
                   ("发展", "fā zhǎn", "to develop", [1, 3]), ("改变", "gǎi biàn", "to change", [3, 4]),
                   ("容易", "róng yì", "easy", [2, 4]), ("慢慢", "màn màn", "slowly", [4, 4])],
     "sentences": [_s("王明|Wáng_Míng|Wang_Ming 到达|dào_dá|arrives 城市|chéng_shì|city 以后|yǐ_hòu|afterward ， 有|yǒu|has 新|xīn|new 工作|gōng_zuò|work 。"),
                   _s("城市|chéng_shì|city 的|de|'s 环境|huán_jìng|environment 很|hěn|very 好|hǎo|good ， 交通|jiāo_tōng|traffic 很|hěn|very 忙|máng|busy 。"),
                   _s("经理|jīng_lǐ|manager 给|gěi|gives 他|tā|him 一个|yí_gè|one 机会|jī_huì|opportunity 。"),
                   _s("王明|Wáng_Míng|Wang_Ming 的|de|'s 目标|mù_biāo|goal 是|shì|is 好好|hǎo_hǎo|well 工作|gōng_zuò|work 。"),
                   _s("这个|zhè_ge|this 过程|guò_chéng|process 不|bù|not 容易|róng_yì|easy ， 他|tā|he 慢慢|màn_màn|slowly 发展|fā_zhǎn|develops 。"),
                   _s("三个月|sān_gè_yuè|three_months 以后|yǐ_hòu|later ， 他|tā|he 的|de|'s 工作|gōng_zuò|work 改变|gǎi_biàn|changes 了|le|(done) 。")],
     "en": "After Wang Ming arrives in the city, he starts new work. The city's environment is good, but traffic is busy. The manager gives him an opportunity. Wang Ming's goal is to do the work well. The process is not easy, but he slowly develops. Three months later, his life has changed.",
     "qs": [{"q": "What is busy in the city?", "choices": ["traffic", "the moon", "the library", "the cake"], "a": 0},
            {"q": "What is Wang Ming's goal?", "choices": ["to do the work well", "to leave the city", "to buy tea", "to sleep late"], "a": 0},
            {"q": "What changes later?", "choices": ["his life", "the weather only", "the map", "the birthday"], "a": 0}]},
    {"id": "r6-4", "level": "R6", "title": "安娜的中文课", "title_en": "Anna's Chinese class",
     "intro": "A study story that links grammar, review, exams, and advice.",
     "new_words": [("课程", "kè chéng", "course", [4, 2]), ("语法", "yǔ fǎ", "grammar", [3, 3]),
                   ("句子", "jù zi", "sentence", [4, 5]), ("复习", "fù xí", "to review", [4, 2]),
                   ("考试", "kǎo shì", "exam", [3, 4]), ("成绩", "chéng jì", "grade; result", [2, 4]),
                   ("建议", "jiàn yì", "suggestion", [4, 4]), ("关系", "guān xi", "relationship", [1, 5]),
                   ("词", "cí", "word", [2]), ("写", "xiě", "to write", [3])],
     "sentences": [_s("安娜|Ān_nà|Anna 的|de|'s 中文|zhōng_wén|Chinese 课程|kè_chéng|course 很|hěn|very 忙|máng|busy 。"),
                   _s("老师|lǎo_shī|teacher 每天|měi_tiān|every_day 说|shuō|says 一个|yí_gè|one 语法|yǔ_fǎ|grammar 点|diǎn|point 。"),
                   _s("学生|xué_sheng|students 写|xiě|write 新|xīn|new 词|cí|words 和|hé|and 句子|jù_zi|sentences 。"),
                   _s("考试|kǎo_shì|exam 以前|yǐ_qián|before ， 安娜|Ān_nà|Anna 认真|rèn_zhēn|carefully 复习|fù_xí|reviews 。"),
                   _s("她|tā|her 的|de|'s 成绩|chéng_jì|grade 很|hěn|very 好|hǎo|good ， 老师|lǎo_shī|teacher 给|gěi|gives 她|tā|her 一个|yí_gè|one 建议|jiàn_yì|suggestion 。"),
                   _s("老师|lǎo_shī|teacher 说|shuō|says ： “ 词|cí|words 和|hé|and 句子|jù_zi|sentences 有|yǒu|have 关系|guān_xi|relationship ， 要|yào|must 一起|yì_qǐ|together 学习|xué_xí|study 。 ”")],
     "en": "Anna's Chinese course is busy. The teacher teaches one grammar point every day. Students use new words to write sentences. Before the exam, Anna reviews carefully. Her grade is good, and the teacher gives her a suggestion: words and sentences are connected and should be studied together.",
     "qs": [{"q": "What does the teacher teach every day?", "choices": ["one grammar point", "a birthday song", "a route", "a job task"], "a": 0},
            {"q": "What does Anna do before the exam?", "choices": ["reviews carefully", "goes to the airport", "sleeps all day", "buys a cake"], "a": 0},
            {"q": "What is the teacher's advice about?", "choices": ["words and sentences are connected", "never review", "only read maps", "avoid grammar"], "a": 0}]},

    {"id": "r7-1", "level": "R7", "title": "慢慢变好", "title_en": "Getting better slowly",
     "intro": "A longer reflective chapter about reading, history, and attitude.",
     "new_words": [("文章", "wén zhāng", "article", [2, 1]), ("世界", "shì jiè", "world", [4, 4]),
                   ("历史", "lì shǐ", "history", [4, 3]), ("文化", "wén huà", "culture", [2, 4]),
                   ("社会", "shè huì", "society", [4, 4]), ("影响", "yǐng xiǎng", "influence", [3, 3]),
                   ("态度", "tài dù", "attitude", [4, 4]), ("讨论", "tǎo lùn", "to discuss", [3, 4]),
                   ("决定", "jué dìng", "to decide", [2, 4]), ("重要", "zhòng yào", "important", [4, 4])],
     "sentences": [_s("安娜|Ān_nà|Anna 每天|měi_tiān|every_day 看|kàn|reads 文章|wén_zhāng|articles 。"),
                   _s("文章|wén_zhāng|article 说|shuō|says ， 学习|xué_xí|studying 汉语|Hàn_yǔ|Chinese 会|huì|can 给|gěi|give 你|nǐ|you 一个|yí_gè|one 世界|shì_jiè|world 。"),
                   _s("这个|zhè_ge|this 世界|shì_jiè|world 里|lǐ|inside 有|yǒu|has 历史|lì_shǐ|history 、 文化|wén_huà|culture 和|hé|and 社会|shè_huì|society 。"),
                   _s("一个|yí_gè|one 小|xiǎo|small 词|cí|word 也|yě|also 会|huì|can 影响|yǐng_xiǎng|influence 一个人|yí_gè_rén|one_person 的|de|'s 态度|tài_dù|attitude 。"),
                   _s("课|kè|class 后|hòu|after ， 安娜|Ān_nà|Anna 和|hé|and 同学|tóng_xué|classmates 讨论|tǎo_lùn|discuss 这个|zhè_ge|this 文章|wén_zhāng|article 。"),
                   _s("她|tā|she 决定|jué_dìng|decides 每天|měi_tiān|every_day 写|xiě|write 一个|yí_gè|one 句子|jù_zi|sentence ， 每天|měi_tiān|every_day 学习|xué_xí|study 也|yě|also 很|hěn|very 重要|zhòng_yào|important 。")],
     "en": "Anna begins reading longer articles. One article says that studying a language can open a world. Inside that world are history, culture and society. Even a small word can influence a person's attitude. After class, Anna and her classmates discuss the article. She decides to write one sentence every day, because small practice is also important.",
     "qs": [{"q": "What can studying a language open?", "choices": ["a world", "a bank account", "a cake box", "a bus door"], "a": 0},
            {"q": "What do Anna and classmates discuss?", "choices": ["the article", "a birthday", "a route", "a price"], "a": 0},
            {"q": "What does Anna decide to do daily?", "choices": ["write one sentence", "take a plane", "work overtime", "copy maps"], "a": 0}]},
    {"id": "r7-2", "level": "R7", "title": "一个城市问题", "title_en": "A city problem",
     "intro": "A second stretch chapter connecting news, science, education, and civic choices.",
     "new_words": [("科学", "kē xué", "science", [1, 2]), ("教育", "jiào yù", "education", [4, 4]),
                   ("政府", "zhèng fǔ", "government", [4, 3]), ("保护", "bǎo hù", "to protect", [3, 4]),
                   ("污染", "wū rǎn", "pollution", [1, 3]), ("经济", "jīng jì", "economy", [1, 4]),
                   ("新闻", "xīn wén", "news", [1, 2]), ("网站", "wǎng zhàn", "website", [3, 4]),
                   ("成功", "chéng gōng", "to succeed", [2, 1]), ("失败", "shī bài", "to fail", [1, 4]),
                   ("问题", "wèn tí", "problem", [4, 2]), ("可能", "kě néng", "maybe; possible", [3, 2])],
     "sentences": [_s("王明|Wáng_Míng|Wang_Ming 在|zài|on 网站|wǎng_zhàn|website 上|shàng|on 看|kàn|reads 新闻|xīn_wén|news 。"),
                   _s("新闻|xīn_wén|news 说|shuō|says ， 一个|yí_gè|one 城市|chéng_shì|city 有|yǒu|has 污染|wū_rǎn|pollution 问题|wèn_tí|problem 。"),
                   _s("老师|lǎo_shī|teacher 和|hé|and 学生|xué_sheng|students 讨论|tǎo_lùn|discuss 这个|zhè_ge|this 科学|kē_xué|science 问题|wèn_tí|problem 。"),
                   _s("学生|xué_sheng|students 说|shuō|say ， 教育|jiào_yù|education 会|huì|can 改变|gǎi_biàn|change 想法|xiǎng_fǎ|ideas 。"),
                   _s("政府|zhèng_fǔ|government 要|yào|needs_to 保护|bǎo_hù|protect 环境|huán_jìng|environment ， 也|yě|also 要|yào|needs_to 看|kàn|look_at 经济|jīng_jì|economy 。"),
                   _s("这个|zhè_ge|this 计划|jì_huà|plan 可能|kě_néng|may 成功|chéng_gōng|succeed ， 也|yě|also 可能|kě_néng|may 失败|shī_bài|fail 。"),
                   _s("王明|Wáng_Míng|Wang_Ming 写下|xiě_xià|writes_down 一个|yí_gè|one 目标|mù_biāo|goal ： 学习|xué_xí|study ， 帮助|bāng_zhù|help 城市|chéng_shì|city 。")],
     "en": "Wang Ming reads news on a website. The news says a city has a pollution problem. The teacher asks students to discuss the problem with scientific methods. Students say education can change habits. The government needs to protect the environment and also consider the economy. The plan may succeed or fail. Wang Ming writes down a goal: first study, then help the city.",
     "qs": [{"q": "Where does Wang Ming read the news?", "choices": ["on a website", "in a restaurant", "at the airport", "on a cake"], "a": 0},
            {"q": "What problem does the city have?", "choices": ["pollution", "no birthdays", "too many libraries", "no students"], "a": 0},
            {"q": "What is Wang Ming's goal?", "choices": ["study, then help the city", "leave the city forever", "stop reading", "buy a phone"], "a": 0}]},
]

_LEVEL_IDX = {lv["id"]: lv["idx"] for lv in LEVELS}
_BY_ID = {t["id"]: t for t in TEXTS}


def get_text(tid):
    return _BY_ID.get(tid)


def _level_complete(done, level_id):
    return all(t["id"] in done for t in TEXTS if t["level"] == level_id)


def open_through(state, stage_idx):
    """Highest open level index: sequential progress, with the speaking stage
    as a floor so a placed learner starts reading at their level."""
    done = state.get("reader", {})
    first_incomplete = len(LEVELS) - 1
    for lv in LEVELS:
        if not _level_complete(done, lv["id"]):
            first_incomplete = lv["idx"]
            break
    return min(len(LEVELS) - 1, max(first_incomplete, stage_idx))


def next_text(state, stage_idx):
    """The next unread text in an open level, in ladder order — what the
    recommendation engine points at."""
    done = state.get("reader", {})
    limit = open_through(state, stage_idx)
    for t in TEXTS:
        if _LEVEL_IDX[t["level"]] <= limit and t["id"] not in done:
            return t
    return None


def view(state, stage_idx):
    """The Read tab's payload: levels with per-text status, no bodies."""
    done = state.get("reader", {})
    limit = open_through(state, stage_idx)
    nxt = next_text(state, stage_idx)
    levels = []
    for lv in LEVELS:
        texts = [{"id": t["id"], "title": t["title"], "title_en": t["title_en"],
                  "words": len(t["new_words"]),
                  "done": t["id"] in done,
                  "score": done.get(t["id"], {}).get("score")}
                 for t in TEXTS if t["level"] == lv["id"]]
        levels.append({**{k: lv[k] for k in ("id", "idx", "zh", "name", "desc", "ruby")},
                       "open": lv["idx"] <= limit,
                       "complete": _level_complete(done, lv["id"]),
                       "texts": texts})
    return {"levels": levels, "open_through": limit,
            "next": nxt["id"] if nxt else None,
            "read_count": len(done), "text_count": len(TEXTS)}


def text_payload(tid):
    """Full text for the reader view (adds the level's ruby default)."""
    t = get_text(tid)
    if not t:
        return None
    return {**t, "new_words": [{"hanzi": w[0], "pinyin": w[1], "english": w[2],
                                "tones": w[3]} for w in t["new_words"]],
            "ruby": LEVELS[_LEVEL_IDX[t["level"]]]["ruby"]}


def complete(state, tid, score):
    """Mark a text read and return the new words that should join the SRS deck
    (caller adds them via learner.add_word — reading builds the vocabulary)."""
    t = get_text(tid)
    if not t:
        return None
    import datetime
    state.setdefault("reader", {})[tid] = {
        "date": datetime.date.today().isoformat(), "score": score}
    return t["new_words"]


# ── Shadowing (Phase 3) ────────────────────────────────────────────────────────
_MARKS = {c: n for cs, n in (("āēīōūǖ", 1), ("áéíóúǘ", 2),
                             ("ǎěǐǒǔǚ", 3), ("àèìòùǜ", 4)) for c in cs}


def _tone_of(syllable):
    for ch in syllable.lower():
        if ch in _MARKS:
            return _MARKS[ch]
    return 5


def sentence_tones(tokens):
    """Expected tone sequence for a tokenized sentence, from token pinyin."""
    tones = []
    for tok in tokens:
        if tok["p"]:
            tones += [_tone_of(s) for s in tok["p"].split()]
    return tones


def shadow_sentences(state, stage_idx, n=5):
    """Sentences worth mirroring: drawn from texts the learner has COMPLETED
    (they know the words; now the prosody), newest first, longest-first within
    a text so the drill has substance. Falls back to open-level texts."""
    done = state.get("reader", {})
    limit = open_through(state, stage_idx)
    pool = [t for t in TEXTS if t["id"] in done]
    if not pool:
        pool = [t for t in TEXTS if _LEVEL_IDX[t["level"]] <= limit]
    pool = pool[::-1][:6]                            # newest completed texts
    out = []
    for t in pool:
        sents = sorted(t["sentences"], key=lambda s: -len(s["t"]))
        for s in sents[:2]:
            zh = "".join(tok["z"] for tok in s["t"])
            tones = sentence_tones(s["t"])
            if len(tones) < 3:                       # too short to shadow
                continue
            out.append({"id": f"{t['id']}:{zh[:12]}", "zh": zh,
                        "text": t["title"], "tones": tones})
            if len(out) >= n:
                return out
    return out
